import Homogenization.Sobolev.Foundations.Cutoff.Euclidean
import Homogenization.Sobolev.Foundations.Cutoff.DerivativeBounds
import Homogenization.Sobolev.Foundations.Cutoff.Profile
import Mathlib.Analysis.Calculus.ContDiff.Basic
import Mathlib.Analysis.Calculus.ContDiff.FTaylorSeries
import Mathlib.Analysis.Calculus.ContDiff.Operations

noncomputable section

open scoped Topology
open Set

namespace Homogenization

/-!
# Ball cutoffs on `Vec d`

This file builds the smooth squared-radius cutoff formula using the explicit
Euclidean balls from `Cutoff.Euclidean`.
-/

namespace QuantitativeTransitionProfile

/-- Squared-radius interpolation variable for a Euclidean ball cutoff. -/
def ballArgument {d : ℕ} (x₀ : Vec d) (r s : ℝ) (x : Vec d) : ℝ :=
  (s ^ 2 - euclideanSqDist x x₀) / (s ^ 2 - r ^ 2)

/-- Ball cutoff generated by a one-dimensional transition profile. -/
def ballCutoff {d : ℕ} (θ : QuantitativeTransitionProfile) (x₀ : Vec d)
    (r s : ℝ) (x : Vec d) : ℝ :=
  θ (ballArgument x₀ r s x)

private theorem ballArgument_den_pos {r s : ℝ} (hr : 0 < r) (hrs : r < s) :
    0 < s ^ 2 - r ^ 2 := by
  have hs : 0 < s := lt_trans hr hrs
  nlinarith [mul_pos (sub_pos.mpr hrs) (add_pos hs hr)]

private theorem iteratedFDeriv_two_coord_sub_const_eq_zero_ball {d : ℕ}
    (i : Fin d) (c : Vec d) :
    iteratedFDeriv ℝ 2 (fun y : Vec d => y i - c i) = 0 := by
  ext x m
  have hx0 : iteratedFDeriv ℝ 2 (fun y : Vec d => y i - c i) x = 0 := by
    apply norm_eq_zero.mp
    rw [← norm_iteratedFDeriv_fderiv]
    have hconst :
        fderiv ℝ (fun y : Vec d => y i - c i) = fun _ => ContinuousLinearMap.proj i := by
      funext y
      rw [fderiv_sub_const]
      change fderiv ℝ (⇑(ContinuousLinearMap.proj (R := ℝ) i)) y = ContinuousLinearMap.proj i
      rw [ContinuousLinearMap.fderiv]
    rw [hconst, iteratedFDeriv_const_of_ne (𝕜 := ℝ) (by norm_num)
      (ContinuousLinearMap.proj i)]
    simp
  simpa using congrArg (fun F : ContinuousMultilinearMap ℝ (fun _ : Fin 2 => Vec d) ℝ => F m) hx0

private theorem fderiv_coord_sub_const_apply_basisVec_ball {d : ℕ}
    (i j : Fin d) (c x : Vec d) :
    (fderiv ℝ (fun y : Vec d => y i - c i) x) (basisVec j) =
      if j = i then 1 else 0 := by
  rw [fderiv_sub_const]
  change (fderiv ℝ (⇑(ContinuousLinearMap.proj (R := ℝ) i)) x) (basisVec j) = _
  rw [ContinuousLinearMap.fderiv]
  simp [basisVec_apply, eq_comm]

private theorem norm_fderiv_coord_sub_const_le_one_ball {d : ℕ}
    (i : Fin d) (c x : Vec d) :
    ‖fderiv ℝ (fun y : Vec d => y i - c i) x‖ ≤ 1 := by
  have hsum := norm_clm_le_sum_basisVec_apply (fderiv ℝ (fun y : Vec d => y i - c i) x)
  calc
    ‖fderiv ℝ (fun y : Vec d => y i - c i) x‖
        ≤ ∑ j : Fin d, ‖(fderiv ℝ (fun y : Vec d => y i - c i) x) (basisVec j)‖ := hsum
    _ = 1 := by
          rw [Finset.sum_eq_single i]
          · simp [fderiv_coord_sub_const_apply_basisVec_ball]
          · intro j _hj hji
            simp [fderiv_coord_sub_const_apply_basisVec_ball, hji]
          · intro hi
            exact False.elim (hi (Finset.mem_univ i))

private theorem norm_iteratedFDeriv_two_coord_sub_const_sq_le_ball {d : ℕ}
    (i : Fin d) (c x : Vec d) :
    ‖iteratedFDeriv ℝ 2 (fun y : Vec d => (y i - c i) ^ 2) x‖ ≤ 2 := by
  let g : Vec d → ℝ := fun y => y i - c i
  have hg : ContDiff ℝ (2 : ℕ) g := by
    simpa [g] using ((contDiff_apply ℝ ℝ i).sub contDiff_const)
  have hmul := norm_iteratedFDeriv_mul_le (𝕜 := ℝ) (A := ℝ) hg hg x le_rfl
  have hzero : ‖iteratedFDeriv ℝ 2 g x‖ = 0 := by
    rw [iteratedFDeriv_two_coord_sub_const_eq_zero_ball, Pi.zero_apply, norm_zero]
  have hone : ‖iteratedFDeriv ℝ 1 g x‖ ≤ 1 := by
    have hnorm :
        ‖iteratedFDeriv ℝ 1 g x‖ = ‖fderiv ℝ g x‖ := by
      simpa [norm_iteratedFDeriv_zero] using
        (norm_iteratedFDeriv_fderiv (𝕜 := ℝ) (f := g) (n := 0) (x := x)).symm
    rw [hnorm]
    simpa [g] using norm_fderiv_coord_sub_const_le_one_ball i c x
  have hval : ‖iteratedFDeriv ℝ 0 g x‖ = ‖g x‖ := by
    simp [g]
  have hsq : (fun y : Vec d => (y i - c i) ^ 2) = fun y : Vec d => g y * g y := by
    funext y
    simp [g, pow_two]
  rw [hsq]
  calc
    ‖iteratedFDeriv ℝ 2 (fun y : Vec d => g y * g y) x‖
        ≤ ∑ k ∈ Finset.range (2 + 1),
            ((2).choose k : ℝ) * ‖iteratedFDeriv ℝ k g x‖ * ‖iteratedFDeriv ℝ (2 - k) g x‖ := hmul
    _ ≤ 2 := by
          have hone_nonneg : 0 ≤ ‖iteratedFDeriv ℝ 1 g x‖ := norm_nonneg _
          have hsum :
              ∑ k ∈ Finset.range (2 + 1),
                  ((2).choose k : ℝ) * ‖iteratedFDeriv ℝ k g x‖ * ‖iteratedFDeriv ℝ (2 - k) g x‖
                =
                ‖g x‖ * ‖iteratedFDeriv ℝ 2 g x‖ +
                  2 * ‖iteratedFDeriv ℝ 1 g x‖ * ‖iteratedFDeriv ℝ 1 g x‖ +
                  ‖iteratedFDeriv ℝ 2 g x‖ * ‖g x‖ := by
            rw [Finset.sum_range_succ, Finset.sum_range_succ, Finset.sum_range_one]
            simp [hval]
          rw [hsum, hzero]
          have hmid : 2 * ‖iteratedFDeriv ℝ 1 g x‖ * ‖iteratedFDeriv ℝ 1 g x‖ ≤ 2 := by
            nlinarith
          linarith

/-- Exact coordinate-direction derivative of the ball interpolation variable. -/
theorem fderiv_ballArgument_apply_basisVec {d : ℕ}
    (x₀ : Vec d) (r s : ℝ) (j : Fin d) (x : Vec d) :
    (fderiv ℝ (ballArgument x₀ r s) x) (basisVec j) =
      (-(2 * (x j - x₀ j))) / (s ^ 2 - r ^ 2) := by
  unfold ballArgument
  simp only [div_eq_mul_inv]
  rw [fderiv_mul_const]
  · rw [fderiv_const_sub]
    simp [fderiv_euclideanSqDist_apply_basisVec, neg_mul]
    ring
  · exact ((contDiff_const.sub (contDiff_euclideanSqDist_left x₀)).differentiable
      (by simp : (1 : WithTop ℕ∞) ≤ (⊤ : ℕ∞))) x

/-- On the outer closed ball, the ball interpolation variable has first
derivative of size at most `2 d / (s - r)` in the default product/sup norm on
`Vec d`. -/
theorem norm_fderiv_ballArgument_le_of_mem_euclideanClosedBall {d : ℕ}
    {x₀ : Vec d} {r s : ℝ} (hr : 0 < r) (hrs : r < s) {x : Vec d}
    (hx : x ∈ euclideanClosedBall x₀ s) :
    ‖fderiv ℝ (ballArgument x₀ r s) x‖ ≤ 2 * (d : ℝ) / (s - r) := by
  have hsum := norm_clm_le_sum_basisVec_apply (fderiv ℝ (ballArgument x₀ r s) x)
  have hs_pos : 0 < s := lt_trans hr hrs
  have hden_pos := ballArgument_den_pos hr hrs
  have hgap_pos : 0 < s - r := sub_pos.mpr hrs
  calc
    ‖fderiv ℝ (ballArgument x₀ r s) x‖
        ≤ ∑ j : Fin d, ‖(fderiv ℝ (ballArgument x₀ r s) x) (basisVec j)‖ := hsum
    _ ≤ ∑ _j : Fin d, 2 * s / (s ^ 2 - r ^ 2) := by
          apply Finset.sum_le_sum
          intro j _hj
          rw [fderiv_ballArgument_apply_basisVec]
          rw [Real.norm_eq_abs, abs_div, abs_of_pos hden_pos]
          have hcoord_sq : (x j - x₀ j) ^ 2 ≤ s ^ 2 :=
            (sq_coord_sub_le_euclideanSqDist x x₀ j).trans hx
          have hcoord_abs : |x j - x₀ j| ≤ s :=
            abs_le_of_sq_le_sq hcoord_sq hs_pos.le
          have hnum : |-(2 * (x j - x₀ j))| ≤ 2 * s := by
            rw [abs_neg, abs_mul, abs_of_pos (by norm_num : (0 : ℝ) < 2)]
            nlinarith [hcoord_abs, abs_nonneg (x j - x₀ j)]
          exact div_le_div_of_nonneg_right hnum hden_pos.le
    _ = (d : ℝ) * (2 * s / (s ^ 2 - r ^ 2)) := by
      simp
    _ ≤ 2 * (d : ℝ) / (s - r) := by
          have hden_eq : s ^ 2 - r ^ 2 = (s - r) * (s + r) := by
            ring
          rw [hden_eq]
          have hsr_pos : 0 < s + r := add_pos hs_pos hr
          rw [mul_div_assoc]
          have hbase : 2 * (s / ((s - r) * (s + r))) ≤ 2 / (s - r) := by
            rw [show 2 * (s / ((s - r) * (s + r))) =
                2 * s / ((s - r) * (s + r)) by ring]
            rw [div_le_div_iff₀ (mul_pos hgap_pos hsr_pos) hgap_pos]
            nlinarith [hr, hs_pos]
          calc
            (d : ℝ) * (2 * (s / ((s - r) * (s + r))))
                ≤ (d : ℝ) * (2 / (s - r)) :=
              mul_le_mul_of_nonneg_left hbase (Nat.cast_nonneg d)
            _ = 2 * (d : ℝ) / (s - r) := by
              ring

/-- Global second-derivative bound for the ball interpolation variable. -/
theorem norm_iteratedFDeriv_two_ballArgument_le {d : ℕ}
    {x₀ : Vec d} {r s : ℝ} (hr : 0 < r) (hrs : r < s) (x : Vec d) :
    ‖iteratedFDeriv ℝ 2 (ballArgument x₀ r s) x‖ ≤ 2 * (d : ℝ) / (s - r) ^ 2 := by
  have hden_pos := ballArgument_den_pos hr hrs
  let f : Vec d → ℝ := (-(1 / (s ^ 2 - r ^ 2))) • fun y => euclideanSqDist y x₀
  let g : Vec d → ℝ := fun _ => s ^ 2 / (s ^ 2 - r ^ 2)
  have hfun :
      ballArgument x₀ r s = fun y : Vec d => f y + g y := by
    funext y
    simp [f, g]
    unfold ballArgument
    field_simp [hden_pos.ne']
    ring
  rw [hfun]
  have heuc2 : ContDiff ℝ (2 : ℕ) (fun y : Vec d => euclideanSqDist y x₀) :=
    (contDiff_euclideanSqDist_left x₀).of_le
      (ENat.natCast_le_of_coe_top_le_withTop le_rfl 2)
  have hf2 : ContDiff ℝ (2 : ℕ) f := by
    simpa [f] using
      ((contDiff_const : ContDiff ℝ (2 : ℕ)
        (fun _ : Vec d => (-(1 / (s ^ 2 - r ^ 2)) : ℝ))).smul heuc2)
  have hg2 : ContDiff ℝ (2 : ℕ) g := by
    simpa [g] using (contDiff_const : ContDiff ℝ (2 : ℕ) g)
  have hsum :
      iteratedFDeriv ℝ 2 (fun y : Vec d => f y + g y) x =
        iteratedFDeriv ℝ 2 f x + iteratedFDeriv ℝ 2 g x := by
    simpa using
      congrArg (fun F : Vec d → ContinuousMultilinearMap ℝ (fun _ : Fin 2 => Vec d) ℝ => F x)
        (iteratedFDeriv_add (𝕜 := ℝ) (i := 2) (f := f) (g := g) hf2 hg2)
  rw [hsum]
  have hg_zero : iteratedFDeriv ℝ 2 g x = 0 := by
    have hg_zero_fun :
        iteratedFDeriv ℝ 2 (fun _ : Vec d => s ^ 2 / (s ^ 2 - r ^ 2)) = 0 :=
      iteratedFDeriv_const_of_ne (𝕜 := ℝ) (E := Vec d) (F := ℝ)
        (n := 2) (by norm_num : 2 ≠ 0) (s ^ 2 / (s ^ 2 - r ^ 2))
    exact congrArg (fun F : Vec d → ContinuousMultilinearMap ℝ (fun _ : Fin 2 => Vec d) ℝ => F x)
      (by simpa [g] using hg_zero_fun)
  rw [hg_zero, add_zero]
  have hsq :
      ‖iteratedFDeriv ℝ 2 f x‖
        =
      (1 / (s ^ 2 - r ^ 2)) *
        ‖iteratedFDeriv ℝ 2 (fun y : Vec d => euclideanSqDist y x₀) x‖ := by
    have hiter :
        iteratedFDeriv ℝ 2 f x =
          (-(1 / (s ^ 2 - r ^ 2)) : ℝ) •
            iteratedFDeriv ℝ 2 (fun y : Vec d => euclideanSqDist y x₀) x := by
      rw [show f = (-(1 / (s ^ 2 - r ^ 2)) : ℝ) • fun y : Vec d => euclideanSqDist y x₀ by
        rfl]
      rw [iteratedFDeriv_const_smul_apply]
      exact heuc2.contDiffAt
    rw [hiter, norm_smul]
    have hscalar_neg : -(1 / (s ^ 2 - r ^ 2)) < 0 := by
      nlinarith [one_div_pos.mpr hden_pos]
    rw [Real.norm_eq_abs, abs_of_neg hscalar_neg]
    ring
  calc
    ‖iteratedFDeriv ℝ 2 f x‖
        = (1 / (s ^ 2 - r ^ 2)) * ‖iteratedFDeriv ℝ 2 (fun y : Vec d => euclideanSqDist y x₀) x‖ :=
      hsq
    _ 
        ≤ (1 / (s ^ 2 - r ^ 2)) * (2 * (d : ℝ)) :=
      by
        have heuc_bound :
            ‖iteratedFDeriv ℝ 2 (fun y : Vec d => euclideanSqDist y x₀) x‖ ≤ 2 * (d : ℝ) := by
          have hfun : (fun y : Vec d => euclideanSqDist y x₀) =
              (fun y : Vec d => ∑ i : Fin d, (y i - x₀ i) ^ 2) := by
            funext y
            simp [euclideanSqDist, vecNormSq, vecDot, pow_two]
          rw [hfun]
          rw [iteratedFDeriv_sum]
          · calc
              ‖(∑ i : Fin d, iteratedFDeriv ℝ 2 (fun y : Vec d => (y i - x₀ i) ^ 2)) x‖ =
                  ‖∑ i : Fin d, iteratedFDeriv ℝ 2 (fun y : Vec d => (y i - x₀ i) ^ 2) x‖ := by
                    simp
              _ ≤ ∑ i : Fin d, ‖iteratedFDeriv ℝ 2 (fun y : Vec d => (y i - x₀ i) ^ 2) x‖ := by
                    simpa using norm_sum_le
                      (Finset.univ : Finset (Fin d))
                      (fun i : Fin d => iteratedFDeriv ℝ 2 (fun y : Vec d => (y i - x₀ i) ^ 2) x)
              _ ≤ ∑ _i : Fin d, 2 := by
                    refine Finset.sum_le_sum ?_
                    intro i _hi
                    exact norm_iteratedFDeriv_two_coord_sub_const_sq_le_ball i x₀ x
              _ = 2 * (d : ℝ) := by
                    simp
                    ring
          · intro i _hi
            exact (((contDiff_apply ℝ ℝ i).sub contDiff_const).pow 2)
        exact mul_le_mul_of_nonneg_left
          heuc_bound
          (le_of_lt (one_div_pos.mpr hden_pos))
    _ ≤ 2 * (d : ℝ) / (s - r) ^ 2 := by
      have hgap_pos : 0 < s - r := sub_pos.mpr hrs
      have hs_pos : 0 < s := lt_trans hr hrs
      have haux : (s - r) ^ 2 ≤ s ^ 2 - r ^ 2 := by
        nlinarith [hr, hs_pos]
      have hrecip : 1 / (s ^ 2 - r ^ 2) ≤ 1 / (s - r) ^ 2 := by
        exact one_div_le_one_div_of_le (by positivity) haux
      have hd_nonneg : 0 ≤ 2 * (d : ℝ) := mul_nonneg (by norm_num) (Nat.cast_nonneg d)
      calc
        (1 / (s ^ 2 - r ^ 2)) * (2 * (d : ℝ))
            ≤ (1 / (s - r) ^ 2) * (2 * (d : ℝ)) :=
          mul_le_mul_of_nonneg_right hrecip hd_nonneg
        _ = 2 * (d : ℝ) / (s - r) ^ 2 := by ring

theorem ballCutoff_smooth {d : ℕ} (θ : QuantitativeTransitionProfile)
    (x₀ : Vec d) {r s : ℝ} (hr : 0 < r) (hrs : r < s) :
    ContDiff ℝ (⊤ : ℕ∞) (ballCutoff θ x₀ r s) := by
  have hden : ∀ _x : Vec d, s ^ 2 - r ^ 2 ≠ 0 :=
    fun _ => (ballArgument_den_pos hr hrs).ne'
  have harg : ContDiff ℝ (⊤ : ℕ∞) (ballArgument x₀ r s) := by
    unfold ballArgument
    exact (contDiff_const.sub (contDiff_euclideanSqDist_left x₀)).div contDiff_const hden
  exact θ.smooth.comp harg

theorem ballCutoff_nonneg {d : ℕ} (θ : QuantitativeTransitionProfile)
    (x₀ : Vec d) (r s : ℝ) (x : Vec d) :
    0 ≤ ballCutoff θ x₀ r s x :=
  θ.nonneg _

theorem ballCutoff_le_one {d : ℕ} (θ : QuantitativeTransitionProfile)
    (x₀ : Vec d) (r s : ℝ) (x : Vec d) :
    ballCutoff θ x₀ r s x ≤ 1 :=
  θ.le_one _

theorem ballCutoff_eq_one_of_mem_euclideanBall {d : ℕ}
    (θ : QuantitativeTransitionProfile) {x₀ : Vec d} {r s : ℝ}
    (hr : 0 < r) (hrs : r < s) {x : Vec d}
    (hx : x ∈ euclideanBall x₀ r) :
    ballCutoff θ x₀ r s x = 1 := by
  unfold ballCutoff
  apply θ.one_of_one_le
  unfold euclideanBall at hx
  unfold ballArgument
  have hden : 0 < s ^ 2 - r ^ 2 := ballArgument_den_pos hr hrs
  rw [one_le_div hden]
  have hlt : euclideanSqDist x x₀ < r ^ 2 := by
    simpa using hx
  nlinarith [hlt.le]

theorem ballCutoff_eq_zero_of_notMem_euclideanClosedBall {d : ℕ}
    (θ : QuantitativeTransitionProfile) {x₀ : Vec d} {r s : ℝ}
    (hr : 0 < r) (hrs : r < s) {x : Vec d}
    (hx : x ∉ euclideanClosedBall x₀ s) :
    ballCutoff θ x₀ r s x = 0 := by
  unfold ballCutoff
  apply θ.zero_of_nonpos
  unfold euclideanClosedBall at hx
  unfold ballArgument
  have hden_nonneg : 0 ≤ s ^ 2 - r ^ 2 :=
    (ballArgument_den_pos hr hrs).le
  have hnum_nonpos : s ^ 2 - euclideanSqDist x x₀ ≤ 0 := by
    have hnot : ¬ euclideanSqDist x x₀ ≤ s ^ 2 := by
      simpa using hx
    have hlt : s ^ 2 < euclideanSqDist x x₀ := not_le.mp hnot
    nlinarith
  exact div_nonpos_of_nonpos_of_nonneg hnum_nonpos hden_nonneg

theorem ballCutoff_support_subset_euclideanClosedBall {d : ℕ}
    (θ : QuantitativeTransitionProfile) {x₀ : Vec d} {r s : ℝ}
    (hr : 0 < r) (hrs : r < s) :
    Function.support (ballCutoff θ x₀ r s) ⊆ euclideanClosedBall x₀ s := by
  intro x hx
  by_contra hnot
  exact hx (ballCutoff_eq_zero_of_notMem_euclideanClosedBall θ hr hrs hnot)

theorem ballCutoff_tsupport_subset_euclideanClosedBall {d : ℕ}
    (θ : QuantitativeTransitionProfile) {x₀ : Vec d} {r s : ℝ}
    (hr : 0 < r) (hrs : r < s) :
    tsupport (ballCutoff θ x₀ r s) ⊆ euclideanClosedBall x₀ s :=
  closure_minimal
    (ballCutoff_support_subset_euclideanClosedBall θ hr hrs)
    (isClosed_euclideanClosedBall x₀ s)

theorem ballCutoff_hasCompactSupport {d : ℕ}
    (θ : QuantitativeTransitionProfile) {x₀ : Vec d} {r s : ℝ}
    (hr : 0 < r) (hrs : r < s) :
    HasCompactSupport (ballCutoff θ x₀ r s) := by
  have hs_nonneg : 0 ≤ s := le_of_lt (lt_trans hr hrs)
  exact HasCompactSupport.of_support_subset_isCompact
    (isCompact_euclideanClosedBall x₀ hs_nonneg)
    (ballCutoff_support_subset_euclideanClosedBall θ hr hrs)

/-- Global first-derivative bound for the ball cutoff with an intermediate
support radius. -/
theorem norm_fderiv_ballCutoff_le {d : ℕ}
    (θ : QuantitativeTransitionProfile) {x₀ : Vec d} {r s : ℝ}
    (hr : 0 < r) (hrs : r < s) (x : Vec d) :
    ‖fderiv ℝ (ballCutoff θ x₀ r s) x‖ ≤
      θ.derivBound * (2 * (d : ℝ) / (s - r)) := by
  by_cases hx : x ∈ euclideanClosedBall x₀ s
  · have hargdiff : DifferentiableAt ℝ (ballArgument x₀ r s) x := by
      have hden : ∀ _x : Vec d, s ^ 2 - r ^ 2 ≠ 0 :=
        fun _ => (ballArgument_den_pos hr hrs).ne'
      exact ((contDiff_const.sub (contDiff_euclideanSqDist_left x₀)).div
        contDiff_const hden).differentiable
          (by simp : (1 : WithTop ℕ∞) ≤ (⊤ : ℕ∞)) x
    calc
      ‖fderiv ℝ (ballCutoff θ x₀ r s) x‖
          = ‖fderiv ℝ (fun y : Vec d => θ (ballArgument x₀ r s y)) x‖ := rfl
      _ ≤ θ.derivBound * ‖fderiv ℝ (ballArgument x₀ r s) x‖ :=
        norm_fderiv_profile_comp_le θ hargdiff
      _ ≤ θ.derivBound * (2 * (d : ℝ) / (s - r)) :=
        mul_le_mul_of_nonneg_left
          (norm_fderiv_ballArgument_le_of_mem_euclideanClosedBall hr hrs hx)
          θ.derivBound_nonneg
  · have hx_support : x ∉ tsupport (ballCutoff θ x₀ r s) := fun hxs =>
      hx (ballCutoff_tsupport_subset_euclideanClosedBall θ hr hrs hxs)
    rw [fderiv_of_notMem_tsupport (𝕜 := ℝ) hx_support, norm_zero]
    exact mul_nonneg θ.derivBound_nonneg
      (div_nonneg (mul_nonneg (by norm_num) (Nat.cast_nonneg d))
        (le_of_lt (sub_pos.mpr hrs)))

/-- Global second-derivative bound for the ball cutoff with an intermediate
support radius. -/
theorem norm_iteratedFDeriv_two_ballCutoff_le {d : ℕ}
    (θ : QuantitativeTransitionProfile) {x₀ : Vec d} {r s : ℝ}
    (hr : 0 < r) (hrs : r < s) (x : Vec d) :
    ‖iteratedFDeriv ℝ 2 (ballCutoff θ x₀ r s) x‖ ≤
      2 * (max 1 (max θ.derivBound θ.secondDerivBound)) *
        (2 * (d : ℝ) / (s - r)) ^ 2 := by
  by_cases hx : x ∈ euclideanClosedBall x₀ s
  · have hargTop : ContDiff ℝ (⊤ : ℕ∞) (ballArgument x₀ r s) := by
      have hden : ∀ _x : Vec d, s ^ 2 - r ^ 2 ≠ 0 :=
        fun _ => (ballArgument_den_pos hr hrs).ne'
      unfold ballArgument
      exact (contDiff_const.sub (contDiff_euclideanSqDist_left x₀)).div contDiff_const hden
    have hargContDiff : ContDiff ℝ (2 : ℕ) (ballArgument x₀ r s) :=
      hargTop.of_le (ENat.natCast_le_of_coe_top_le_withTop le_rfl 2)
    have hfirst :
        ‖iteratedFDeriv ℝ 1 (ballArgument x₀ r s) x‖ ≤ 2 * (d : ℝ) / (s - r) := by
      have hnorm :
          ‖iteratedFDeriv ℝ 1 (ballArgument x₀ r s) x‖ =
            ‖fderiv ℝ (ballArgument x₀ r s) x‖ := by
        simpa [norm_iteratedFDeriv_zero] using
          (norm_iteratedFDeriv_fderiv (𝕜 := ℝ) (f := ballArgument x₀ r s) (n := 0) (x := x)).symm
      rw [hnorm]
      exact norm_fderiv_ballArgument_le_of_mem_euclideanClosedBall (x₀ := x₀) hr hrs hx
    have hsecond := norm_iteratedFDeriv_two_ballArgument_le (x₀ := x₀) hr hrs x
    have hbase_nonneg : 0 ≤ 2 * (d : ℝ) / (s - r) := by
      exact div_nonneg (mul_nonneg (by norm_num) (Nat.cast_nonneg d)) (le_of_lt (sub_pos.mpr hrs))
    have hsecond' : ‖iteratedFDeriv ℝ 2 (ballArgument x₀ r s) x‖ ≤
        (2 * (d : ℝ) / (s - r)) ^ 2 := by
      have hsq_le : 2 * (d : ℝ) ≤ (2 * (d : ℝ)) ^ 2 := by
        cases d with
        | zero =>
            norm_num
        | succ d =>
            have hd_one : (1 : ℝ) ≤ ((Nat.succ d : ℕ) : ℝ) := by
              exact_mod_cast Nat.succ_le_succ (Nat.zero_le d)
            nlinarith
      calc
        ‖iteratedFDeriv ℝ 2 (ballArgument x₀ r s) x‖ ≤ 2 * (d : ℝ) / (s - r) ^ 2 := hsecond
        _ ≤ (2 * (d : ℝ) / (s - r)) ^ 2 := by
          have hden_nonneg : 0 ≤ (s - r) ^ 2 := sq_nonneg (s - r)
          have hsquare :
              (2 * (d : ℝ) / (s - r)) ^ 2 = ((2 * (d : ℝ)) ^ 2) / (s - r) ^ 2 := by
            field_simp [pow_two]
          rw [hsquare]
          exact div_le_div_of_nonneg_right hsq_le hden_nonneg
    exact norm_iteratedFDeriv_two_profile_comp_le θ hargContDiff hfirst hsecond'
  · have hx_support : x ∉ tsupport (ballCutoff θ x₀ r s) := fun hxs =>
      hx (ballCutoff_tsupport_subset_euclideanClosedBall θ hr hrs hxs)
    have hx_iter :
        x ∉ Function.support (iteratedFDeriv ℝ 2 (ballCutoff θ x₀ r s)) := by
      intro hxs
      exact hx_support ((support_iteratedFDeriv_subset (𝕜 := ℝ) (f := ballCutoff θ x₀ r s) 2) hxs)
    have hzero : iteratedFDeriv ℝ 2 (ballCutoff θ x₀ r s) x = 0 := by
      simpa [Function.support] using hx_iter
    rw [hzero, norm_zero]
    positivity

theorem ballCutoff_tsupport_subset_euclideanBall {d : ℕ}
    (θ : QuantitativeTransitionProfile) {x₀ : Vec d} {r s R : ℝ}
    (hr : 0 < r) (hrs : r < s) (hsR : s < R) :
    tsupport (ballCutoff θ x₀ r s) ⊆ euclideanBall x₀ R := by
  have hs_nonneg : 0 ≤ s := le_of_lt (lt_trans hr hrs)
  exact (ballCutoff_tsupport_subset_euclideanClosedBall θ hr hrs).trans
    (euclideanClosedBall_subset_euclideanBall hs_nonneg hsR)

end QuantitativeTransitionProfile

end Homogenization
