import Homogenization.Geometry.CubeMetric
import Homogenization.Sobolev.Foundations.Cutoff.DerivativeBounds
import Homogenization.Sobolev.Foundations.Cutoff.Profile
import Mathlib.Algebra.Order.BigOperators.Ring.Finset
import Mathlib.Analysis.Calculus.ContDiff.Basic
import Mathlib.Analysis.Calculus.ContDiff.Operations

noncomputable section

open scoped BigOperators Topology
open Set

namespace Homogenization

/-!
# Cube cutoffs from one-dimensional profiles

This file contains the coordinate-product construction for smooth cutoffs
between concentric subcubes of a triadic cube.
-/

/-- Closed concentric subcube of relative radius `ρ` inside a triadic cube. -/
def scaledClosedCubeSet {d : ℕ} (Q : TriadicCube d) (ρ : ℝ) : Set (Vec d) :=
  {x | ∀ i, |x i - cubeCenter Q i| ≤ ρ * cubeRadius Q}

/-- Open concentric subcube of relative radius `ρ` inside a triadic cube. -/
def scaledOpenCubeSet {d : ℕ} (Q : TriadicCube d) (ρ : ℝ) : Set (Vec d) :=
  {x | ∀ i, |x i - cubeCenter Q i| < ρ * cubeRadius Q}

theorem scaledClosedCubeSet_subset_metricClosedBall {d : ℕ}
    (Q : TriadicCube d) {ρ : ℝ} (hρ : 0 ≤ ρ) :
    scaledClosedCubeSet Q ρ ⊆ Metric.closedBall (cubeCenter Q) (ρ * cubeRadius Q) := by
  intro x hx
  rw [Metric.mem_closedBall, dist_pi_le_iff]
  · intro i
    simpa [Real.dist_eq, abs_sub_comm] using hx i
  · exact mul_nonneg hρ (cubeRadius_nonneg Q)

theorem isClosed_scaledClosedCubeSet {d : ℕ} (Q : TriadicCube d) (ρ : ℝ) :
    IsClosed (scaledClosedCubeSet Q ρ) := by
  classical
  unfold scaledClosedCubeSet
  rw [show {x : Vec d | ∀ i, |x i - cubeCenter Q i| ≤ ρ * cubeRadius Q} =
      ⋂ i : Fin d, {x : Vec d | |x i - cubeCenter Q i| ≤ ρ * cubeRadius Q} by
    ext x
    simp]
  exact isClosed_iInter fun i =>
    isClosed_Iic.preimage
      ((continuous_abs.comp ((continuous_apply i).sub continuous_const)))

theorem isCompact_scaledClosedCubeSet {d : ℕ} (Q : TriadicCube d) {ρ : ℝ}
    (hρ : 0 ≤ ρ) :
    IsCompact (scaledClosedCubeSet Q ρ) :=
  (ProperSpace.isCompact_closedBall (cubeCenter Q) (ρ * cubeRadius Q)).of_isClosed_subset
    (isClosed_scaledClosedCubeSet Q ρ)
    (scaledClosedCubeSet_subset_metricClosedBall Q hρ)

namespace QuantitativeTransitionProfile

/-- Squared coordinate interpolation variable for the `i`th face of a cube
cutoff. -/
def cubeArgument {d : ℕ} (Q : TriadicCube d) (ρ₁ ρ₂ : ℝ) (i : Fin d)
    (x : Vec d) : ℝ :=
  ((ρ₂ * cubeRadius Q) ^ 2 - (x i - cubeCenter Q i) ^ 2) /
    ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2)

/-- Coordinate-product cube cutoff generated by a one-dimensional profile. -/
def cubeCutoff {d : ℕ} (θ : QuantitativeTransitionProfile) (Q : TriadicCube d)
    (ρ₁ ρ₂ : ℝ) (x : Vec d) : ℝ :=
  ∏ i : Fin d, θ (cubeArgument Q ρ₁ ρ₂ i x)

/-- Single profile factor appearing in the coordinate-product cube cutoff. -/
def cubeFactor {d : ℕ} (θ : QuantitativeTransitionProfile) (Q : TriadicCube d)
    (ρ₁ ρ₂ : ℝ) (i : Fin d) (x : Vec d) : ℝ :=
  θ (cubeArgument Q ρ₁ ρ₂ i x)

/-- Partial coordinate-product used to build the full cube cutoff by induction
over a finite set of coordinates. -/
def partialCubeCutoff {d : ℕ} (θ : QuantitativeTransitionProfile) (Q : TriadicCube d)
    (ρ₁ ρ₂ : ℝ) (u : Finset (Fin d)) (x : Vec d) : ℝ :=
  ∏ i ∈ u, cubeFactor θ Q ρ₁ ρ₂ i x

private theorem cubeArgument_den_pos {d : ℕ} (Q : TriadicCube d)
    {ρ₁ ρ₂ : ℝ} (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) :
    0 < (ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2 := by
  have hrad : 0 < cubeRadius Q := cubeRadius_pos Q
  have hρ₂ : 0 < ρ₂ := lt_trans hρ₁ hρ₁₂
  have hleft : 0 < ρ₂ * cubeRadius Q := mul_pos hρ₂ hrad
  have hright : 0 < ρ₁ * cubeRadius Q := mul_pos hρ₁ hrad
  have hlt : ρ₁ * cubeRadius Q < ρ₂ * cubeRadius Q :=
    mul_lt_mul_of_pos_right hρ₁₂ hrad
  calc
    0 < (ρ₂ * cubeRadius Q - ρ₁ * cubeRadius Q) *
        (ρ₂ * cubeRadius Q + ρ₁ * cubeRadius Q) :=
      mul_pos (sub_pos.mpr hlt) (add_pos hleft hright)
    _ = (ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2 := by ring

/-- Exact coordinate-direction derivative of the one-dimensional cube argument. -/
theorem fderiv_cubeArgument_apply_basisVec {d : ℕ} (Q : TriadicCube d)
    (ρ₁ ρ₂ : ℝ) (i j : Fin d) (x : Vec d) :
    (fderiv ℝ (cubeArgument Q ρ₁ ρ₂ i) x) (basisVec j) =
      (-(2 * (x i - cubeCenter Q i) * (if j = i then 1 else 0))) /
        ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2) := by
  unfold cubeArgument
  simp only [div_eq_mul_inv]
  rw [fderiv_mul_const]
  · rw [fderiv_const_sub]
    simp [fderiv_coord_sub_const_sq_apply_basisVec, neg_mul, mul_assoc]
    split <;> ring
  · fun_prop

/-- The cube cutoff argument is differentiable whenever the annulus radii are
strictly ordered. -/
theorem differentiableAt_cubeArgument {d : ℕ} (Q : TriadicCube d)
    {ρ₁ ρ₂ : ℝ} (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) (i : Fin d) (x : Vec d) :
    DifferentiableAt ℝ (cubeArgument Q ρ₁ ρ₂ i) x := by
  have hden : ∀ _x : Vec d,
      (ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2 ≠ 0 :=
    fun _ => (cubeArgument_den_pos Q hρ₁ hρ₁₂).ne'
  have hcoord : ContDiff ℝ (⊤ : ℕ∞)
      (fun y : Vec d => y i - cubeCenter Q i) :=
    (contDiff_apply ℝ ℝ i).sub contDiff_const
  exact ((contDiff_const.sub (hcoord.pow 2)).div contDiff_const hden).differentiable
    (by simp : (1 : WithTop ℕ∞) ≤ (⊤ : ℕ∞)) x

/-- On the outer closed cube, each one-dimensional cube argument has the
expected first-derivative scale. -/
theorem norm_fderiv_cubeArgument_le_of_mem_scaledClosedCubeSet {d : ℕ}
    (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) {i : Fin d} {x : Vec d}
    (hx : x ∈ scaledClosedCubeSet Q ρ₂) :
    ‖fderiv ℝ (cubeArgument Q ρ₁ ρ₂ i) x‖ ≤
      2 / ((ρ₂ - ρ₁) * cubeRadius Q) := by
  have hsum := norm_clm_le_sum_basisVec_apply (fderiv ℝ (cubeArgument Q ρ₁ ρ₂ i) x)
  have hrad_pos : 0 < cubeRadius Q := cubeRadius_pos Q
  have hρ₂_pos : 0 < ρ₂ := lt_trans hρ₁ hρ₁₂
  have hden_pos := cubeArgument_den_pos Q hρ₁ hρ₁₂
  have hgap_pos : 0 < (ρ₂ - ρ₁) * cubeRadius Q :=
    mul_pos (sub_pos.mpr hρ₁₂) hrad_pos
  calc
    ‖fderiv ℝ (cubeArgument Q ρ₁ ρ₂ i) x‖
        ≤ ∑ j : Fin d,
            ‖(fderiv ℝ (cubeArgument Q ρ₁ ρ₂ i) x) (basisVec j)‖ := hsum
    _ = ‖(-(2 * (x i - cubeCenter Q i) * (if i = i then 1 else 0))) /
        ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2)‖ := by
          rw [Finset.sum_eq_single i]
          · simp [fderiv_cubeArgument_apply_basisVec]
          · intro j _hj hji
            simp [fderiv_cubeArgument_apply_basisVec, hji]
          · intro hi
            exact False.elim (hi (Finset.mem_univ i))
    _ ≤ 2 / ((ρ₂ - ρ₁) * cubeRadius Q) := by
          have habs : |x i - cubeCenter Q i| ≤ ρ₂ * cubeRadius Q := hx i
          rw [if_pos rfl]
          rw [Real.norm_eq_abs, abs_div]
          rw [abs_of_pos hden_pos]
          have hnum : |-(2 * (x i - cubeCenter Q i) * 1)| ≤
              2 * (ρ₂ * cubeRadius Q) := by
            rw [abs_neg, mul_one, abs_mul, abs_of_pos (by norm_num : (0 : ℝ) < 2)]
            exact mul_le_mul_of_nonneg_left habs (by norm_num : 0 ≤ (2 : ℝ))
          have hden_eq : ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2) =
              ((ρ₂ - ρ₁) * cubeRadius Q) * ((ρ₂ + ρ₁) * cubeRadius Q) := by
            ring
          have hright_pos : 0 < (ρ₂ + ρ₁) * cubeRadius Q := by
            positivity
          have hbound : 2 * (ρ₂ * cubeRadius Q) /
                (((ρ₂ - ρ₁) * cubeRadius Q) * ((ρ₂ + ρ₁) * cubeRadius Q))
              ≤ 2 / ((ρ₂ - ρ₁) * cubeRadius Q) := by
            rw [div_le_div_iff₀ (mul_pos hgap_pos hright_pos) hgap_pos]
            nlinarith [mul_pos hρ₂_pos hrad_pos, mul_pos hρ₁ hrad_pos]
          calc
            |-(2 * (x i - cubeCenter Q i) * 1)| /
                ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2)
                ≤ 2 * (ρ₂ * cubeRadius Q) /
                    ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2) :=
              div_le_div_of_nonneg_right hnum hden_pos.le
            _ = 2 * (ρ₂ * cubeRadius Q) /
                (((ρ₂ - ρ₁) * cubeRadius Q) * ((ρ₂ + ρ₁) * cubeRadius Q)) := by
              rw [hden_eq]
            _ ≤ 2 / ((ρ₂ - ρ₁) * cubeRadius Q) := hbound

/-- Global second-derivative bound for each one-dimensional cube argument. -/
theorem norm_iteratedFDeriv_two_cubeArgument_le {d : ℕ}
    (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) (i : Fin d) (x : Vec d) :
    ‖iteratedFDeriv ℝ 2 (cubeArgument Q ρ₁ ρ₂ i) x‖ ≤
      2 / (((ρ₂ - ρ₁) * cubeRadius Q) ^ 2) := by
  have hden_pos := cubeArgument_den_pos Q hρ₁ hρ₁₂
  let f : Vec d → ℝ :=
    (-(1 / ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2))) •
      (fun y : Vec d => (y i - cubeCenter Q i) ^ 2)
  let g : Vec d → ℝ := fun _ =>
    (ρ₂ * cubeRadius Q) ^ 2 / ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2)
  have hfun : cubeArgument Q ρ₁ ρ₂ i = fun y : Vec d => f y + g y := by
    funext y
    simp [f, g]
    unfold cubeArgument
    field_simp [hden_pos.ne']
    ring
  rw [hfun]
  have hsq2 : ContDiff ℝ (2 : ℕ) (fun y : Vec d => (y i - cubeCenter Q i) ^ 2) := by
    exact (((contDiff_apply ℝ ℝ i).sub contDiff_const).pow 2)
  have hf2 : ContDiff ℝ (2 : ℕ) f := by
    simpa [f] using
      ((contDiff_const : ContDiff ℝ (2 : ℕ)
        (fun _ : Vec d => (-(1 / ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2)) : ℝ))).smul
        hsq2)
  have hg2 : ContDiff ℝ (2 : ℕ) g := by
    simpa [g] using (contDiff_const : ContDiff ℝ (2 : ℕ) g)
  have hsum :
      iteratedFDeriv ℝ 2 (fun y : Vec d => f y + g y) x =
        iteratedFDeriv ℝ 2 f x + iteratedFDeriv ℝ 2 g x := by
    simpa using
      congrArg (fun F : Vec d → ContinuousMultilinearMap ℝ (fun _ : Fin 2 => Vec d) ℝ => F x)
        (iteratedFDeriv_add (𝕜 := ℝ) (i := 2) (f := f) (g := g) hf2 hg2)
  rw [hsum]
  have hg_zero : iteratedFDeriv ℝ 2 g x = 0 := by
    have hg_zero_fun :
        iteratedFDeriv ℝ 2
            (fun _ : Vec d =>
              (ρ₂ * cubeRadius Q) ^ 2 / ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2)) = 0 :=
      iteratedFDeriv_const_of_ne (𝕜 := ℝ) (E := Vec d) (F := ℝ)
        (n := 2) (by norm_num : 2 ≠ 0)
        ((ρ₂ * cubeRadius Q) ^ 2 / ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2))
    exact congrArg
      (fun F : Vec d → ContinuousMultilinearMap ℝ (fun _ : Fin 2 => Vec d) ℝ => F x)
      (by simpa [g] using hg_zero_fun)
  rw [hg_zero, add_zero]
  have hsq :
      ‖iteratedFDeriv ℝ 2 f x‖ =
        (1 / ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2)) *
          ‖iteratedFDeriv ℝ 2 (fun y : Vec d => (y i - cubeCenter Q i) ^ 2) x‖ := by
    have hiter :
        iteratedFDeriv ℝ 2 f x =
          (-(1 / ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2)) : ℝ) •
            iteratedFDeriv ℝ 2 (fun y : Vec d => (y i - cubeCenter Q i) ^ 2) x := by
      rw [show f =
          (-(1 / ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2)) : ℝ) •
            (fun y : Vec d => (y i - cubeCenter Q i) ^ 2) by rfl]
      rw [iteratedFDeriv_const_smul_apply]
      exact hsq2.contDiffAt
    rw [hiter, norm_smul]
    have hscalar_neg : -(1 / ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2)) < 0 := by
      exact neg_neg_of_pos (one_div_pos.mpr hden_pos)
    rw [Real.norm_eq_abs, abs_of_neg hscalar_neg]
    ring
  calc
    ‖iteratedFDeriv ℝ 2 f x‖
        =
      (1 / ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2)) *
        ‖iteratedFDeriv ℝ 2 (fun y : Vec d => (y i - cubeCenter Q i) ^ 2) x‖ := hsq
    _ ≤ (1 / ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2)) * 2 := by
      exact mul_le_mul_of_nonneg_left
        (norm_iteratedFDeriv_two_coord_sub_const_sq_le i (cubeCenter Q) x)
        (le_of_lt (one_div_pos.mpr hden_pos))
    _ ≤ 2 / (((ρ₂ - ρ₁) * cubeRadius Q) ^ 2) := by
      have hrad_pos : 0 < cubeRadius Q := cubeRadius_pos Q
      have hρ₂_pos : 0 < ρ₂ := lt_trans hρ₁ hρ₁₂
      have haux :
          ((ρ₂ - ρ₁) * cubeRadius Q) ^ 2 ≤
            (ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2 := by
        nlinarith [hρ₁, hρ₂_pos, hrad_pos]
      have hrecip :
          1 / ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2) ≤
            1 / (((ρ₂ - ρ₁) * cubeRadius Q) ^ 2) := by
        have hsq_pos : 0 < ((ρ₂ - ρ₁) * cubeRadius Q) ^ 2 := by
          exact sq_pos_of_pos (mul_pos (sub_pos.mpr hρ₁₂) (cubeRadius_pos Q))
        exact one_div_le_one_div_of_le hsq_pos haux
      calc
        (1 / ((ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2)) * 2
            ≤ (1 / (((ρ₂ - ρ₁) * cubeRadius Q) ^ 2)) * 2 :=
          mul_le_mul_of_nonneg_right hrecip (by norm_num)
        _ = 2 / (((ρ₂ - ρ₁) * cubeRadius Q) ^ 2) := by ring

theorem cubeFactor_contDiff_two {d : ℕ} (θ : QuantitativeTransitionProfile)
    (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ} (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) (i : Fin d) :
    ContDiff ℝ (2 : ℕ) (cubeFactor θ Q ρ₁ ρ₂ i) := by
  have hθ : ContDiff ℝ (2 : ℕ) θ := by
    exact θ.smooth.of_le (ENat.natCast_le_of_coe_top_le_withTop le_rfl 2)
  have hden : ∀ _x : Vec d,
      (ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2 ≠ 0 :=
    fun _ => (cubeArgument_den_pos Q hρ₁ hρ₁₂).ne'
  have hcoord : ContDiff ℝ (2 : ℕ) (fun x : Vec d => x i - cubeCenter Q i) := by
    exact ((contDiff_apply ℝ ℝ i).sub contDiff_const).of_le
      (ENat.natCast_le_of_coe_top_le_withTop le_rfl 2)
  have harg : ContDiff ℝ (2 : ℕ) (cubeArgument Q ρ₁ ρ₂ i) := by
    unfold cubeArgument
    exact (contDiff_const.sub (hcoord.pow 2)).div contDiff_const hden
  simpa [cubeFactor] using hθ.comp harg

/-- Inside the `i`th inner slab, the `i`th one-dimensional cube factor is
locally constant, hence its full Frechet derivative vanishes. -/
theorem fderiv_cubeFactor_eq_zero_of_abs_sub_center_lt_inner {d : ℕ}
    (θ : QuantitativeTransitionProfile) (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) {i : Fin d} {x : Vec d}
    (hx : |x i - cubeCenter Q i| < ρ₁ * cubeRadius Q) :
    fderiv ℝ (cubeFactor θ Q ρ₁ ρ₂ i) x = 0 := by
  let S : Set (Vec d) := {y | |y i - cubeCenter Q i| < ρ₁ * cubeRadius Q}
  have hS_open : IsOpen S := by
    dsimp [S]
    exact isOpen_lt
      (continuous_abs.comp ((continuous_apply i).sub continuous_const))
      continuous_const
  have hloc : cubeFactor θ Q ρ₁ ρ₂ i =ᶠ[𝓝 x] fun _ => (1 : ℝ) := by
    filter_upwards [hS_open.mem_nhds hx] with y hy
    unfold cubeFactor cubeArgument
    apply θ.one_of_one_le
    rw [one_le_div (cubeArgument_den_pos Q hρ₁ hρ₁₂)]
    have hrad_nonneg : 0 ≤ cubeRadius Q := cubeRadius_nonneg Q
    have hρ₁_nonneg : 0 ≤ ρ₁ := le_of_lt hρ₁
    have habs : |y i - cubeCenter Q i| ≤ ρ₁ * cubeRadius Q := le_of_lt hy
    have hsquare :
        (y i - cubeCenter Q i) ^ 2 ≤ (ρ₁ * cubeRadius Q) ^ 2 := by
      rw [sq_le_sq]
      simpa [abs_of_nonneg (mul_nonneg hρ₁_nonneg hrad_nonneg)] using habs
    linarith
  simpa using hloc.fderiv_eq

/-- A coordinate direction differentiates only the matching cube factor. -/
theorem fderiv_cubeFactor_apply_basisVec_eq_zero_of_ne {d : ℕ}
    (θ : QuantitativeTransitionProfile) (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) {i k : Fin d} (hik : i ≠ k)
    (x : Vec d) :
    (fderiv ℝ (cubeFactor θ Q ρ₁ ρ₂ k) x) (basisVec i) = 0 := by
  have harg : DifferentiableAt ℝ (cubeArgument Q ρ₁ ρ₂ k) x :=
    differentiableAt_cubeArgument Q hρ₁ hρ₁₂ k x
  have hθ : DifferentiableAt ℝ θ (cubeArgument Q ρ₁ ρ₂ k x) :=
    θ.smooth.differentiable (by simp) (cubeArgument Q ρ₁ ρ₂ k x)
  unfold cubeFactor
  rw [fderiv_comp' (x := x) hθ harg]
  have harg_zero :
      (fderiv ℝ (cubeArgument Q ρ₁ ρ₂ k) x) (basisVec i) = 0 := by
    simp [fderiv_cubeArgument_apply_basisVec, hik]
  rw [ContinuousLinearMap.comp_apply, harg_zero, map_zero]

/-- The canonical coordinate-product cutoff has zero `i`-direction derivative
away from the `i`-normal transition collar. -/
theorem fderiv_cubeCutoff_apply_basisVec_eq_zero_of_abs_sub_center_lt_inner {d : ℕ}
    (θ : QuantitativeTransitionProfile) (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) {i : Fin d} {x : Vec d}
    (hx : |x i - cubeCenter Q i| < ρ₁ * cubeRadius Q) :
    (fderiv ℝ (cubeCutoff θ Q ρ₁ ρ₂) x) (basisVec i) = 0 := by
  classical
  have hfactor_diff : ∀ k : Fin d,
      DifferentiableAt ℝ (fun y : Vec d => θ (cubeArgument Q ρ₁ ρ₂ k y)) x := by
    intro k
    exact (θ.smooth.differentiable (by simp) (cubeArgument Q ρ₁ ρ₂ k x)).comp x
      (differentiableAt_cubeArgument Q hρ₁ hρ₁₂ k x)
  change (fderiv ℝ (fun y : Vec d =>
      ∏ k : Fin d, θ (cubeArgument Q ρ₁ ρ₂ k y)) x) (basisVec i) = 0
  rw [fderiv_finset_prod (u := (Finset.univ : Finset (Fin d)))
    (g := fun k y => θ (cubeArgument Q ρ₁ ρ₂ k y))]
  · simp only [ContinuousLinearMap.sum_apply, ContinuousLinearMap.smul_apply]
    apply Finset.sum_eq_zero
    intro k _hk
    by_cases hki : k = i
    · subst k
      have hderiv_zero :
          fderiv ℝ (fun y : Vec d => θ (cubeArgument Q ρ₁ ρ₂ i y)) x = 0 := by
        simpa [cubeFactor] using
          fderiv_cubeFactor_eq_zero_of_abs_sub_center_lt_inner θ Q hρ₁ hρ₁₂ hx
      simp [hderiv_zero]
    · have hderiv_apply_zero :
          (fderiv ℝ (fun y : Vec d => θ (cubeArgument Q ρ₁ ρ₂ k y)) x)
              (basisVec i) = 0 := by
        have hik : i ≠ k := fun h => hki h.symm
        simpa [cubeFactor] using
          fderiv_cubeFactor_apply_basisVec_eq_zero_of_ne θ Q hρ₁ hρ₁₂ hik x
      simp [hderiv_apply_zero]
  · intro k _hk
    exact hfactor_diff k

theorem norm_iteratedFDeriv_one_cubeFactor_le_of_mem_scaledClosedCubeSet {d : ℕ}
    (θ : QuantitativeTransitionProfile) (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) {i : Fin d} {x : Vec d}
    (hx : x ∈ scaledClosedCubeSet Q ρ₂) :
    ‖iteratedFDeriv ℝ 1 (cubeFactor θ Q ρ₁ ρ₂ i) x‖ ≤
      θ.derivBound * (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by
  have hnorm :
      ‖iteratedFDeriv ℝ 1 (cubeFactor θ Q ρ₁ ρ₂ i) x‖ =
        ‖fderiv ℝ (cubeFactor θ Q ρ₁ ρ₂ i) x‖ := by
    simpa [norm_iteratedFDeriv_zero] using
      (norm_iteratedFDeriv_fderiv (𝕜 := ℝ) (f := cubeFactor θ Q ρ₁ ρ₂ i) (n := 0) (x := x)).symm
  have hargDiff : DifferentiableAt ℝ (cubeArgument Q ρ₁ ρ₂ i) x := by
    have hden : ∀ _x : Vec d,
        (ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2 ≠ 0 :=
      fun _ => (cubeArgument_den_pos Q hρ₁ hρ₁₂).ne'
    have hcoord : ContDiff ℝ (⊤ : ℕ∞) (fun y : Vec d => y i - cubeCenter Q i) :=
      (contDiff_apply ℝ ℝ i).sub contDiff_const
    exact ((contDiff_const.sub (hcoord.pow 2)).div contDiff_const hden).differentiable
      (ENat.natCast_le_of_coe_top_le_withTop le_rfl 1) x
  rw [hnorm]
  calc
    ‖fderiv ℝ (cubeFactor θ Q ρ₁ ρ₂ i) x‖
        ≤ θ.derivBound * ‖fderiv ℝ (cubeArgument Q ρ₁ ρ₂ i) x‖ :=
      norm_fderiv_profile_comp_le θ hargDiff
    _ ≤ θ.derivBound * (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) :=
      mul_le_mul_of_nonneg_left
        (norm_fderiv_cubeArgument_le_of_mem_scaledClosedCubeSet Q hρ₁ hρ₁₂ hx)
        θ.derivBound_nonneg

theorem norm_iteratedFDeriv_two_cubeFactor_le_of_mem_scaledClosedCubeSet {d : ℕ}
    (θ : QuantitativeTransitionProfile) (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) {i : Fin d} {x : Vec d}
    (hx : x ∈ scaledClosedCubeSet Q ρ₂) :
    ‖iteratedFDeriv ℝ 2 (cubeFactor θ Q ρ₁ ρ₂ i) x‖ ≤
      2 * (max 1 (max θ.derivBound θ.secondDerivBound)) *
        (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) ^ 2 := by
  have hfirst :
      ‖iteratedFDeriv ℝ 1 (cubeArgument Q ρ₁ ρ₂ i) x‖ ≤
        2 / ((ρ₂ - ρ₁) * cubeRadius Q) := by
    have hnorm :
        ‖iteratedFDeriv ℝ 1 (cubeArgument Q ρ₁ ρ₂ i) x‖ =
          ‖fderiv ℝ (cubeArgument Q ρ₁ ρ₂ i) x‖ := by
      simpa [norm_iteratedFDeriv_zero] using
        (norm_iteratedFDeriv_fderiv (𝕜 := ℝ) (f := cubeArgument Q ρ₁ ρ₂ i) (n := 0) (x := x)).symm
    rw [hnorm]
    exact norm_fderiv_cubeArgument_le_of_mem_scaledClosedCubeSet Q hρ₁ hρ₁₂ hx
  have hsecond :
      ‖iteratedFDeriv ℝ 2 (cubeArgument Q ρ₁ ρ₂ i) x‖ ≤
        (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) ^ 2 := by
    have hbase := norm_iteratedFDeriv_two_cubeArgument_le Q hρ₁ hρ₁₂ i x
    have hsquare :
        2 / (((ρ₂ - ρ₁) * cubeRadius Q) ^ 2) ≤
          (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) ^ 2 := by
      have hgap_ne : ((ρ₂ - ρ₁) * cubeRadius Q) ≠ 0 := by
        exact ne_of_gt (mul_pos (sub_pos.mpr hρ₁₂) (cubeRadius_pos Q))
      rw [show (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) ^ 2 =
          4 / (((ρ₂ - ρ₁) * cubeRadius Q) ^ 2) by
        field_simp [pow_two, hgap_ne]
        ring]
      exact div_le_div_of_nonneg_right (by norm_num : (2 : ℝ) ≤ 4) (sq_nonneg _)
    exact hbase.trans hsquare
  have hargContDiff : ContDiff ℝ (2 : ℕ) (cubeArgument Q ρ₁ ρ₂ i) := by
    have hden : ∀ _x : Vec d,
        (ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2 ≠ 0 :=
      fun _ => (cubeArgument_den_pos Q hρ₁ hρ₁₂).ne'
    have hcoord : ContDiff ℝ (2 : ℕ) (fun y : Vec d => y i - cubeCenter Q i) := by
      exact ((contDiff_apply ℝ ℝ i).sub contDiff_const).of_le
        (ENat.natCast_le_of_coe_top_le_withTop le_rfl 2)
    unfold cubeArgument
    exact (contDiff_const.sub (hcoord.pow 2)).div contDiff_const hden
  simpa [cubeFactor] using
    norm_iteratedFDeriv_two_profile_comp_le θ hargContDiff hfirst hsecond

theorem cubeCutoff_smooth {d : ℕ} (θ : QuantitativeTransitionProfile)
    (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ} (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) :
    ContDiff ℝ (⊤ : ℕ∞) (cubeCutoff θ Q ρ₁ ρ₂) := by
  unfold cubeCutoff
  apply contDiff_prod
  intro i _hi
  apply θ.smooth.comp
  unfold cubeArgument
  have hden : ∀ _x : Vec d,
      (ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2 ≠ 0 :=
    fun _ => (cubeArgument_den_pos Q hρ₁ hρ₁₂).ne'
  have hcoord : ContDiff ℝ (⊤ : ℕ∞)
      (fun x : Vec d => x i - cubeCenter Q i) :=
    (contDiff_apply ℝ ℝ i).sub contDiff_const
  exact (contDiff_const.sub (hcoord.pow 2)).div contDiff_const hden

theorem cubeCutoff_nonneg {d : ℕ} (θ : QuantitativeTransitionProfile)
    (Q : TriadicCube d) (ρ₁ ρ₂ : ℝ) (x : Vec d) :
    0 ≤ cubeCutoff θ Q ρ₁ ρ₂ x := by
  unfold cubeCutoff
  exact Finset.prod_nonneg (fun i _hi => θ.nonneg _)

theorem cubeCutoff_le_one {d : ℕ} (θ : QuantitativeTransitionProfile)
    (Q : TriadicCube d) (ρ₁ ρ₂ : ℝ) (x : Vec d) :
    cubeCutoff θ Q ρ₁ ρ₂ x ≤ 1 := by
  unfold cubeCutoff
  exact Finset.prod_le_one
    (fun i _hi => θ.nonneg _)
    (fun i _hi => θ.le_one _)

theorem cubeCutoff_eq_one_of_mem_scaledClosedCubeSet {d : ℕ}
    (θ : QuantitativeTransitionProfile) {Q : TriadicCube d} {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) {x : Vec d}
    (hx : x ∈ scaledClosedCubeSet Q ρ₁) :
    cubeCutoff θ Q ρ₁ ρ₂ x = 1 := by
  unfold cubeCutoff
  apply Finset.prod_eq_one
  intro i _hi
  apply θ.one_of_one_le
  unfold cubeArgument
  rw [one_le_div (cubeArgument_den_pos Q hρ₁ hρ₁₂)]
  have hrad_nonneg : 0 ≤ cubeRadius Q := cubeRadius_nonneg Q
  have hρ₁_nonneg : 0 ≤ ρ₁ := le_of_lt hρ₁
  have habs : |x i - cubeCenter Q i| ≤ ρ₁ * cubeRadius Q := hx i
  have hsquare :
      (x i - cubeCenter Q i) ^ 2 ≤ (ρ₁ * cubeRadius Q) ^ 2 := by
    rw [sq_le_sq]
    simpa [abs_of_nonneg (mul_nonneg hρ₁_nonneg hrad_nonneg)] using habs
  linarith

theorem cubeCutoff_eq_zero_of_notMem_scaledOpenCubeSet {d : ℕ}
    (θ : QuantitativeTransitionProfile) {Q : TriadicCube d} {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) {x : Vec d}
    (hx : x ∉ scaledOpenCubeSet Q ρ₂) :
    cubeCutoff θ Q ρ₁ ρ₂ x = 0 := by
  classical
  unfold scaledOpenCubeSet at hx
  have hx' : ¬ ∀ i : Fin d, |x i - cubeCenter Q i| < ρ₂ * cubeRadius Q := by
    simpa using hx
  rw [not_forall] at hx'
  obtain ⟨i, hi⟩ := hx'
  rw [not_lt] at hi
  unfold cubeCutoff
  apply Finset.prod_eq_zero (Finset.mem_univ i)
  apply θ.zero_of_nonpos
  unfold cubeArgument
  have hden_nonneg :
      0 ≤ (ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2 :=
    (cubeArgument_den_pos Q hρ₁ hρ₁₂).le
  have hrad_nonneg : 0 ≤ cubeRadius Q := cubeRadius_nonneg Q
  have hρ₂_nonneg : 0 ≤ ρ₂ := le_of_lt (lt_trans hρ₁ hρ₁₂)
  have hsquare :
      (ρ₂ * cubeRadius Q) ^ 2 ≤ (x i - cubeCenter Q i) ^ 2 := by
    rw [sq_le_sq]
    have hprod_nonneg : 0 ≤ ρ₂ * cubeRadius Q :=
      mul_nonneg hρ₂_nonneg hrad_nonneg
    exact (abs_of_nonneg hprod_nonneg).symm ▸ hi
  have hnum_nonpos :
      (ρ₂ * cubeRadius Q) ^ 2 - (x i - cubeCenter Q i) ^ 2 ≤ 0 := by
    nlinarith
  exact div_nonpos_of_nonpos_of_nonneg hnum_nonpos hden_nonneg

theorem cubeCutoff_support_subset_scaledOpenCubeSet {d : ℕ}
    (θ : QuantitativeTransitionProfile) {Q : TriadicCube d} {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) :
    Function.support (cubeCutoff θ Q ρ₁ ρ₂) ⊆ scaledOpenCubeSet Q ρ₂ := by
  intro x hx
  by_contra hnot
  exact hx (cubeCutoff_eq_zero_of_notMem_scaledOpenCubeSet θ hρ₁ hρ₁₂ hnot)

theorem cubeCutoff_support_subset_scaledClosedCubeSet {d : ℕ}
    (θ : QuantitativeTransitionProfile) {Q : TriadicCube d} {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) :
    Function.support (cubeCutoff θ Q ρ₁ ρ₂) ⊆ scaledClosedCubeSet Q ρ₂ := by
  intro x hx i
  exact le_of_lt ((cubeCutoff_support_subset_scaledOpenCubeSet θ hρ₁ hρ₁₂ hx) i)

theorem cubeCutoff_tsupport_subset_scaledClosedCubeSet {d : ℕ}
    (θ : QuantitativeTransitionProfile) {Q : TriadicCube d} {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) :
    tsupport (cubeCutoff θ Q ρ₁ ρ₂) ⊆ scaledClosedCubeSet Q ρ₂ :=
  closure_minimal
    (cubeCutoff_support_subset_scaledClosedCubeSet θ hρ₁ hρ₁₂)
    (isClosed_scaledClosedCubeSet Q ρ₂)

private theorem partialCubeCutoff_nonneg {d : ℕ} (θ : QuantitativeTransitionProfile)
    (Q : TriadicCube d) (ρ₁ ρ₂ : ℝ) (u : Finset (Fin d)) (x : Vec d) :
    0 ≤ partialCubeCutoff θ Q ρ₁ ρ₂ u x := by
  unfold partialCubeCutoff
  exact Finset.prod_nonneg (fun i _hi => θ.nonneg _)

private theorem partialCubeCutoff_le_one {d : ℕ} (θ : QuantitativeTransitionProfile)
    (Q : TriadicCube d) (ρ₁ ρ₂ : ℝ) (u : Finset (Fin d)) (x : Vec d) :
    partialCubeCutoff θ Q ρ₁ ρ₂ u x ≤ 1 := by
  unfold partialCubeCutoff
  exact Finset.prod_le_one (fun i _hi => θ.nonneg _) (fun i _hi => θ.le_one _)

private theorem norm_iteratedFDeriv_zero_cubeFactor_le_one {d : ℕ}
    (θ : QuantitativeTransitionProfile) (Q : TriadicCube d)
    (ρ₁ ρ₂ : ℝ) (i : Fin d) (x : Vec d) :
    ‖iteratedFDeriv ℝ 0 (cubeFactor θ Q ρ₁ ρ₂ i) x‖ ≤ 1 := by
  rw [norm_iteratedFDeriv_zero, Real.norm_eq_abs]
  simpa [cubeFactor, abs_of_nonneg (θ.nonneg _)] using θ.le_one (cubeArgument Q ρ₁ ρ₂ i x)

private theorem norm_iteratedFDeriv_zero_partialCubeCutoff_le_one {d : ℕ}
    (θ : QuantitativeTransitionProfile) (Q : TriadicCube d)
    (ρ₁ ρ₂ : ℝ) (u : Finset (Fin d)) (x : Vec d) :
    ‖iteratedFDeriv ℝ 0 (partialCubeCutoff θ Q ρ₁ ρ₂ u) x‖ ≤ 1 := by
  rw [norm_iteratedFDeriv_zero, Real.norm_eq_abs,
    abs_of_nonneg (partialCubeCutoff_nonneg θ Q ρ₁ ρ₂ u x)]
  exact partialCubeCutoff_le_one θ Q ρ₁ ρ₂ u x

private theorem partialCubeCutoff_contDiff_two {d : ℕ} (θ : QuantitativeTransitionProfile)
    (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ} (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂)
    (u : Finset (Fin d)) :
    ContDiff ℝ (2 : ℕ) (partialCubeCutoff θ Q ρ₁ ρ₂ u) := by
  unfold partialCubeCutoff
  apply contDiff_prod
  intro i hi
  exact cubeFactor_contDiff_two θ Q hρ₁ hρ₁₂ i

private theorem norm_fderiv_partialCubeCutoff_le {d : ℕ}
    (θ : QuantitativeTransitionProfile) (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) (u : Finset (Fin d)) {x : Vec d}
    (hx : x ∈ scaledClosedCubeSet Q ρ₂) :
    ‖fderiv ℝ (partialCubeCutoff θ Q ρ₁ ρ₂ u) x‖ ≤
      (u.card : ℝ) * (max 1 (max θ.derivBound θ.secondDerivBound)) *
        (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by
  have hfactor_diff : ∀ i ∈ u, DifferentiableAt ℝ (cubeFactor θ Q ρ₁ ρ₂ i) x := by
    intro i hi
    exact (cubeFactor_contDiff_two θ Q hρ₁ hρ₁₂ i).differentiable
      (by norm_num : (1 : WithTop ℕ∞) ≤ (2 : WithTop ℕ∞)) x
  unfold partialCubeCutoff
  rw [fderiv_finset_prod]
  · calc
      ‖∑ i ∈ u, (∏ j ∈ u.erase i, cubeFactor θ Q ρ₁ ρ₂ j x) •
          fderiv ℝ (cubeFactor θ Q ρ₁ ρ₂ i) x‖
          ≤ ∑ i ∈ u, ‖(∏ j ∈ u.erase i, cubeFactor θ Q ρ₁ ρ₂ j x) •
              fderiv ℝ (cubeFactor θ Q ρ₁ ρ₂ i) x‖ := by
        simpa using norm_sum_le (s := u)
          (f := fun i =>
            (∏ j ∈ u.erase i, cubeFactor θ Q ρ₁ ρ₂ j x) •
              fderiv ℝ (cubeFactor θ Q ρ₁ ρ₂ i) x)
      _ ≤ ∑ _i ∈ u,
          (max 1 (max θ.derivBound θ.secondDerivBound)) *
            (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by
        apply Finset.sum_le_sum
        intro i hi
        rw [norm_smul]
        have hprod_nonneg : 0 ≤ ∏ j ∈ u.erase i, cubeFactor θ Q ρ₁ ρ₂ j x :=
          Finset.prod_nonneg fun j hj => θ.nonneg _
        have hprod_le_one : ∏ j ∈ u.erase i, cubeFactor θ Q ρ₁ ρ₂ j x ≤ 1 :=
          Finset.prod_le_one (fun j hj => θ.nonneg _) (fun j hj => θ.le_one _)
        have hfactor_bound :
            ‖fderiv ℝ (cubeFactor θ Q ρ₁ ρ₂ i) x‖ ≤
              (max 1 (max θ.derivBound θ.secondDerivBound)) *
                (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by
          have hnorm :
              ‖iteratedFDeriv ℝ 1 (cubeFactor θ Q ρ₁ ρ₂ i) x‖ =
                ‖fderiv ℝ (cubeFactor θ Q ρ₁ ρ₂ i) x‖ := by
            simpa [norm_iteratedFDeriv_zero] using
              (norm_iteratedFDeriv_fderiv (𝕜 := ℝ) (f := cubeFactor θ Q ρ₁ ρ₂ i)
                (n := 0) (x := x)).symm
          calc
            ‖fderiv ℝ (cubeFactor θ Q ρ₁ ρ₂ i) x‖
                ≤ θ.derivBound * (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by
              rw [← hnorm]
              exact norm_iteratedFDeriv_one_cubeFactor_le_of_mem_scaledClosedCubeSet
                θ Q hρ₁ hρ₁₂ hx
            _ ≤ (max 1 (max θ.derivBound θ.secondDerivBound)) *
                  (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by
              have hDnonneg : 0 ≤ 2 / ((ρ₂ - ρ₁) * cubeRadius Q) := by
                have hgap_pos : 0 < (ρ₂ - ρ₁) * cubeRadius Q := by
                  exact mul_pos (sub_pos.mpr hρ₁₂) (cubeRadius_pos Q)
                positivity
              exact mul_le_mul_of_nonneg_right
                ((le_max_left _ _).trans (le_max_right _ _)) hDnonneg
        calc
          ‖∏ j ∈ u.erase i, cubeFactor θ Q ρ₁ ρ₂ j x‖ *
              ‖fderiv ℝ (cubeFactor θ Q ρ₁ ρ₂ i) x‖
              ≤ 1 * ‖fderiv ℝ (cubeFactor θ Q ρ₁ ρ₂ i) x‖ := by
            gcongr
            simpa [Real.norm_of_nonneg hprod_nonneg] using hprod_le_one
          _ ≤ (max 1 (max θ.derivBound θ.secondDerivBound)) *
                (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by
            simpa using hfactor_bound
      _ = (u.card : ℝ) *
          ((max 1 (max θ.derivBound θ.secondDerivBound)) *
            (2 / ((ρ₂ - ρ₁) * cubeRadius Q))) := by
        simp
      _ = (u.card : ℝ) * (max 1 (max θ.derivBound θ.secondDerivBound)) *
          (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by ring
  · intro i hi
    exact hfactor_diff i hi

private theorem norm_iteratedFDeriv_one_partialCubeCutoff_le {d : ℕ}
    (θ : QuantitativeTransitionProfile) (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) (u : Finset (Fin d)) {x : Vec d}
    (hx : x ∈ scaledClosedCubeSet Q ρ₂) :
    ‖iteratedFDeriv ℝ 1 (partialCubeCutoff θ Q ρ₁ ρ₂ u) x‖ ≤
      (u.card : ℝ) * (max 1 (max θ.derivBound θ.secondDerivBound)) *
        (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by
  have hnorm :
      ‖iteratedFDeriv ℝ 1 (partialCubeCutoff θ Q ρ₁ ρ₂ u) x‖ =
        ‖fderiv ℝ (partialCubeCutoff θ Q ρ₁ ρ₂ u) x‖ := by
    simpa [norm_iteratedFDeriv_zero] using
      (norm_iteratedFDeriv_fderiv (𝕜 := ℝ) (f := partialCubeCutoff θ Q ρ₁ ρ₂ u)
        (n := 0) (x := x)).symm
  rw [hnorm]
  exact norm_fderiv_partialCubeCutoff_le θ Q hρ₁ hρ₁₂ u hx

private theorem norm_iteratedFDeriv_two_partialCubeCutoff_le {d : ℕ}
    (θ : QuantitativeTransitionProfile) (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) :
    ∀ (u : Finset (Fin d)) (x : Vec d), x ∈ scaledClosedCubeSet Q ρ₂ →
      ‖iteratedFDeriv ℝ 2 (partialCubeCutoff θ Q ρ₁ ρ₂ u) x‖ ≤
        2 * (u.card : ℝ) ^ 2 *
          ((max 1 (max θ.derivBound θ.secondDerivBound)) *
            (2 / ((ρ₂ - ρ₁) * cubeRadius Q))) ^ 2 := by
  classical
  intro u
  refine Finset.induction_on u ?_ ?_
  · intro x hx
    have hfun : partialCubeCutoff θ Q ρ₁ ρ₂ ∅ = fun _ : Vec d => (1 : ℝ) := by
      funext y
      simp [partialCubeCutoff]
    rw [hfun]
    have hzero :
        iteratedFDeriv ℝ 2 (fun _ : Vec d => (1 : ℝ)) x = 0 := by
      exact congrArg
        (fun F : Vec d → ContinuousMultilinearMap ℝ (fun _ : Fin 2 => Vec d) ℝ => F x)
        (iteratedFDeriv_const_of_ne (𝕜 := ℝ) (E := Vec d) (F := ℝ)
          (n := 2) (by norm_num : 2 ≠ 0) (1 : ℝ))
    rw [hzero, norm_zero]
    positivity
  · intro i u hi hu x hx
    let A : ℝ := (max 1 (max θ.derivBound θ.secondDerivBound)) *
      (2 / ((ρ₂ - ρ₁) * cubeRadius Q))
    have hA_nonneg : 0 ≤ A := by
      dsimp [A]
      apply mul_nonneg
      · exact le_trans zero_le_one (le_max_left _ _)
      · have hgap_pos : 0 < (ρ₂ - ρ₁) * cubeRadius Q := by
          exact mul_pos (sub_pos.mpr hρ₁₂) (cubeRadius_pos Q)
        positivity
    have hf0 := norm_iteratedFDeriv_zero_cubeFactor_le_one θ Q ρ₁ ρ₂ i x
    have hg0 := norm_iteratedFDeriv_zero_partialCubeCutoff_le_one θ Q ρ₁ ρ₂ u x
    have hf1 : ‖iteratedFDeriv ℝ 1 (cubeFactor θ Q ρ₁ ρ₂ i) x‖ ≤ A := by
      dsimp [A]
      refine (norm_iteratedFDeriv_one_cubeFactor_le_of_mem_scaledClosedCubeSet
        θ Q hρ₁ hρ₁₂ hx).trans ?_
      have hDnonneg : 0 ≤ 2 / ((ρ₂ - ρ₁) * cubeRadius Q) := by
        have hgap_pos : 0 < (ρ₂ - ρ₁) * cubeRadius Q := by
          exact mul_pos (sub_pos.mpr hρ₁₂) (cubeRadius_pos Q)
        positivity
      exact mul_le_mul_of_nonneg_right
        ((le_max_left _ _).trans (le_max_right _ _)) hDnonneg
    have hg1 : ‖iteratedFDeriv ℝ 1 (partialCubeCutoff θ Q ρ₁ ρ₂ u) x‖ ≤ (u.card : ℝ) * A := by
      have htmp := norm_iteratedFDeriv_one_partialCubeCutoff_le θ Q hρ₁ hρ₁₂ u hx
      simpa [A, mul_assoc] using htmp
    have hf2 : ‖iteratedFDeriv ℝ 2 (cubeFactor θ Q ρ₁ ρ₂ i) x‖ ≤ 2 * A ^ 2 := by
      dsimp [A]
      refine (norm_iteratedFDeriv_two_cubeFactor_le_of_mem_scaledClosedCubeSet
        θ Q hρ₁ hρ₁₂ hx).trans ?_
      have hM : 1 ≤ max 1 (max θ.derivBound θ.secondDerivBound) := le_max_left _ _
      have hD_nonneg : 0 ≤ 2 / ((ρ₂ - ρ₁) * cubeRadius Q) := by
        have hgap_pos : 0 < (ρ₂ - ρ₁) * cubeRadius Q := by
          exact mul_pos (sub_pos.mpr hρ₁₂) (cubeRadius_pos Q)
        positivity
      have hD_sq_nonneg : 0 ≤ (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) ^ 2 := sq_nonneg _
      have hMmul :
          2 * max 1 (max θ.derivBound θ.secondDerivBound) *
              (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) ^ 2
            ≤
          2 * (max 1 (max θ.derivBound θ.secondDerivBound) *
              (2 / ((ρ₂ - ρ₁) * cubeRadius Q))) ^ 2 := by
        have hMm : max 1 (max θ.derivBound θ.secondDerivBound) ≤
            (max 1 (max θ.derivBound θ.secondDerivBound)) ^ 2 := by
          nlinarith
        have hmain :
            max 1 (max θ.derivBound θ.secondDerivBound) *
                (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) ^ 2
              ≤
            (max 1 (max θ.derivBound θ.secondDerivBound)) ^ 2 *
                (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) ^ 2 := by
          exact mul_le_mul_of_nonneg_right hMm hD_sq_nonneg
        simpa [pow_two, mul_assoc, mul_left_comm, mul_comm] using
          mul_le_mul_of_nonneg_left hmain (by norm_num : 0 ≤ (2 : ℝ))
      exact hMmul
    have hg2 : ‖iteratedFDeriv ℝ 2 (partialCubeCutoff θ Q ρ₁ ρ₂ u) x‖ ≤
        2 * (u.card : ℝ) ^ 2 * A ^ 2 := by
      have htmp := hu x hx
      simpa [A, mul_assoc] using htmp
    have hprod :
        partialCubeCutoff θ Q ρ₁ ρ₂ (insert i u) =
          fun y => cubeFactor θ Q ρ₁ ρ₂ i y * partialCubeCutoff θ Q ρ₁ ρ₂ u y := by
      funext y
      simp [partialCubeCutoff, Finset.prod_insert, hi]
    rw [hprod]
    have hmul := norm_iteratedFDeriv_mul_le (𝕜 := ℝ)
      (f := cubeFactor θ Q ρ₁ ρ₂ i) (g := partialCubeCutoff θ Q ρ₁ ρ₂ u)
      (cubeFactor_contDiff_two θ Q hρ₁ hρ₁₂ i)
      (partialCubeCutoff_contDiff_two θ Q hρ₁ hρ₁₂ u)
      x le_rfl
    calc
      ‖iteratedFDeriv ℝ 2
          (fun y => cubeFactor θ Q ρ₁ ρ₂ i y * partialCubeCutoff θ Q ρ₁ ρ₂ u y) x‖
          ≤ ∑ k ∈ Finset.range (2 + 1),
              ((2).choose k : ℝ) * ‖iteratedFDeriv ℝ k (cubeFactor θ Q ρ₁ ρ₂ i) x‖ *
                ‖iteratedFDeriv ℝ (2 - k) (partialCubeCutoff θ Q ρ₁ ρ₂ u) x‖ := hmul
      _ =
          ‖iteratedFDeriv ℝ 0 (cubeFactor θ Q ρ₁ ρ₂ i) x‖ *
              ‖iteratedFDeriv ℝ 2 (partialCubeCutoff θ Q ρ₁ ρ₂ u) x‖ +
            2 * ‖iteratedFDeriv ℝ 1 (cubeFactor θ Q ρ₁ ρ₂ i) x‖ *
              ‖iteratedFDeriv ℝ 1 (partialCubeCutoff θ Q ρ₁ ρ₂ u) x‖ +
            ‖iteratedFDeriv ℝ 2 (cubeFactor θ Q ρ₁ ρ₂ i) x‖ *
              ‖iteratedFDeriv ℝ 0 (partialCubeCutoff θ Q ρ₁ ρ₂ u) x‖ := by
        rw [Finset.sum_range_succ, Finset.sum_range_succ, Finset.sum_range_one]
        simp
      _ ≤ 1 * (2 * (u.card : ℝ) ^ 2 * A ^ 2) +
            2 * A * ((u.card : ℝ) * A) +
            (2 * A ^ 2) * 1 := by
        gcongr
      _ ≤ 2 * ((insert i u).card : ℝ) ^ 2 * A ^ 2 := by
        rw [Finset.card_insert_of_notMem hi]
        rw [Nat.cast_add, Nat.cast_one]
        have hsquare :
            ((u.card : ℝ) + 1) ^ 2 = (u.card : ℝ) ^ 2 + 2 * (u.card : ℝ) + 1 := by ring
        rw [hsquare]
        nlinarith [sq_nonneg A]

/-- Global second-derivative bound for the coordinate-product cube cutoff. -/
theorem norm_iteratedFDeriv_two_cubeCutoff_le {d : ℕ}
    (θ : QuantitativeTransitionProfile) (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) (x : Vec d) :
    ‖iteratedFDeriv ℝ 2 (cubeCutoff θ Q ρ₁ ρ₂) x‖ ≤
      2 * (d : ℝ) ^ 2 *
        ((max 1 (max θ.derivBound θ.secondDerivBound)) *
          (2 / ((ρ₂ - ρ₁) * cubeRadius Q))) ^ 2 := by
  by_cases hx : x ∈ scaledClosedCubeSet Q ρ₂
  · have hpartial := norm_iteratedFDeriv_two_partialCubeCutoff_le θ Q hρ₁ hρ₁₂
      (Finset.univ : Finset (Fin d)) x hx
    simpa [cubeCutoff, partialCubeCutoff] using hpartial
  · have hx_support : x ∉ tsupport (cubeCutoff θ Q ρ₁ ρ₂) := fun hxs =>
      hx (cubeCutoff_tsupport_subset_scaledClosedCubeSet θ hρ₁ hρ₁₂ hxs)
    have hx_iter :
        x ∉ Function.support (iteratedFDeriv ℝ 2 (cubeCutoff θ Q ρ₁ ρ₂)) := by
      intro hxs
      exact hx_support
        ((support_iteratedFDeriv_subset (𝕜 := ℝ) (f := cubeCutoff θ Q ρ₁ ρ₂) 2) hxs)
    have hzero : iteratedFDeriv ℝ 2 (cubeCutoff θ Q ρ₁ ρ₂) x = 0 := by
      simpa [Function.support] using hx_iter
    rw [hzero, norm_zero]
    positivity

/-- Global first-derivative bound for the coordinate-product cube cutoff. -/
theorem norm_fderiv_cubeCutoff_le {d : ℕ}
    (θ : QuantitativeTransitionProfile) (Q : TriadicCube d) {ρ₁ ρ₂ : ℝ}
    (hρ₁ : 0 < ρ₁) (hρ₁₂ : ρ₁ < ρ₂) (x : Vec d) :
    ‖fderiv ℝ (cubeCutoff θ Q ρ₁ ρ₂) x‖ ≤
      (d : ℝ) * θ.derivBound * (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by
  by_cases hx : x ∈ scaledClosedCubeSet Q ρ₂
  · have hargdiff : ∀ i : Fin d,
        DifferentiableAt ℝ (cubeArgument Q ρ₁ ρ₂ i) x := by
      intro i
      have hden : ∀ _x : Vec d,
          (ρ₂ * cubeRadius Q) ^ 2 - (ρ₁ * cubeRadius Q) ^ 2 ≠ 0 :=
        fun _ => (cubeArgument_den_pos Q hρ₁ hρ₁₂).ne'
      have hcoord : ContDiff ℝ (⊤ : ℕ∞)
          (fun x : Vec d => x i - cubeCenter Q i) :=
        (contDiff_apply ℝ ℝ i).sub contDiff_const
      exact ((contDiff_const.sub (hcoord.pow 2)).div contDiff_const hden).differentiable
        (by simp : (1 : WithTop ℕ∞) ≤ (⊤ : ℕ∞)) x
    have hfactor_diff : ∀ i : Fin d,
        DifferentiableAt ℝ (fun y : Vec d => θ (cubeArgument Q ρ₁ ρ₂ i y)) x := by
      intro i
      exact (θ.smooth.differentiable (by simp) (cubeArgument Q ρ₁ ρ₂ i x)).comp
        x (hargdiff i)
    change ‖fderiv ℝ
        (fun y : Vec d => ∏ i : Fin d, θ (cubeArgument Q ρ₁ ρ₂ i y)) x‖ ≤
      (d : ℝ) * θ.derivBound * (2 / ((ρ₂ - ρ₁) * cubeRadius Q))
    rw [fderiv_finset_prod (u := (Finset.univ : Finset (Fin d)))
      (g := fun i y => θ (cubeArgument Q ρ₁ ρ₂ i y))]
    · calc
        ‖∑ i ∈ (Finset.univ : Finset (Fin d)),
            (∏ j ∈ (Finset.univ : Finset (Fin d)).erase i,
              θ (cubeArgument Q ρ₁ ρ₂ j x)) •
              fderiv ℝ (fun y : Vec d => θ (cubeArgument Q ρ₁ ρ₂ i y)) x‖
            ≤ ∑ i : Fin d, ‖(∏ j ∈ (Finset.univ : Finset (Fin d)).erase i,
              θ (cubeArgument Q ρ₁ ρ₂ j x)) •
              fderiv ℝ (fun y : Vec d => θ (cubeArgument Q ρ₁ ρ₂ i y)) x‖ := by
          simpa using norm_sum_le
            (Finset.univ : Finset (Fin d))
            (fun i : Fin d =>
              (∏ j ∈ (Finset.univ : Finset (Fin d)).erase i,
                θ (cubeArgument Q ρ₁ ρ₂ j x)) •
                fderiv ℝ (fun y : Vec d => θ (cubeArgument Q ρ₁ ρ₂ i y)) x)
        _ ≤ ∑ _i : Fin d,
            θ.derivBound * (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by
          apply Finset.sum_le_sum
          intro i _hi
          rw [norm_smul]
          have hprod_nonneg : 0 ≤ ∏ j ∈ (Finset.univ : Finset (Fin d)).erase i,
              θ (cubeArgument Q ρ₁ ρ₂ j x) :=
            Finset.prod_nonneg fun j _ => θ.nonneg _
          have hprod_le_one : ∏ j ∈ (Finset.univ : Finset (Fin d)).erase i,
              θ (cubeArgument Q ρ₁ ρ₂ j x) ≤ 1 :=
            Finset.prod_le_one (fun j _ => θ.nonneg _) (fun j _ => θ.le_one _)
          have hfactor_bound :
              ‖fderiv ℝ (fun y : Vec d => θ (cubeArgument Q ρ₁ ρ₂ i y)) x‖ ≤
                θ.derivBound * (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by
            calc
              ‖fderiv ℝ (fun y : Vec d => θ (cubeArgument Q ρ₁ ρ₂ i y)) x‖
                  ≤ θ.derivBound * ‖fderiv ℝ (cubeArgument Q ρ₁ ρ₂ i) x‖ :=
                norm_fderiv_profile_comp_le θ (hargdiff i)
              _ ≤ θ.derivBound * (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) :=
                mul_le_mul_of_nonneg_left
                  (norm_fderiv_cubeArgument_le_of_mem_scaledClosedCubeSet Q hρ₁ hρ₁₂ hx)
                  θ.derivBound_nonneg
          calc
            ‖∏ j ∈ (Finset.univ : Finset (Fin d)).erase i,
                θ (cubeArgument Q ρ₁ ρ₂ j x)‖ *
                ‖fderiv ℝ (fun y : Vec d => θ (cubeArgument Q ρ₁ ρ₂ i y)) x‖
                ≤ 1 * ‖fderiv ℝ
                    (fun y : Vec d => θ (cubeArgument Q ρ₁ ρ₂ i y)) x‖ := by
              gcongr
              simpa [Real.norm_of_nonneg hprod_nonneg] using hprod_le_one
            _ ≤ θ.derivBound * (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by
              simpa using hfactor_bound
        _ = (d : ℝ) * (θ.derivBound * (2 / ((ρ₂ - ρ₁) * cubeRadius Q))) := by
          simp
        _ = (d : ℝ) * θ.derivBound * (2 / ((ρ₂ - ρ₁) * cubeRadius Q)) := by
          ring
    · intro i _hi
      exact hfactor_diff i
  · have hx_support : x ∉ tsupport (cubeCutoff θ Q ρ₁ ρ₂) := fun hxs =>
      hx (cubeCutoff_tsupport_subset_scaledClosedCubeSet θ hρ₁ hρ₁₂ hxs)
    rw [fderiv_of_notMem_tsupport (𝕜 := ℝ) hx_support, norm_zero]
    have hgap_nonneg : 0 ≤ (ρ₂ - ρ₁) * cubeRadius Q :=
      le_of_lt (mul_pos (sub_pos.mpr hρ₁₂) (cubeRadius_pos Q))
    exact mul_nonneg (mul_nonneg (Nat.cast_nonneg d) θ.derivBound_nonneg)
      (div_nonneg (by norm_num) hgap_nonneg)

end QuantitativeTransitionProfile

end Homogenization
