import Homogenization.Book.Ch05.Theorems.Section52.GeometrySeries.DescendantCardinality
import Homogenization.Book.Ch05.Theorems.Section52.GeometrySeries.TwoExponentBounds
import Homogenization.Book.Ch05.Theorems.Section52.GeometrySeries.SmallTailTerm
