import Homogenization.Sobolev.Foundations.CubePoisson.FullVectorPoincare
import Homogenization.Sobolev.Foundations.CubePoisson.FullVectorPoincareL2
import Homogenization.Sobolev.Foundations.CubePoisson.ProjectedVectorPoincare
