import Homogenization.Sobolev.Foundations.PoincareW1p.Seminorms
import Homogenization.Sobolev.Foundations.PoincareW1p.SmoothCase
import Homogenization.Sobolev.Foundations.PoincareW1p.ConvexApproxTendsto
import Homogenization.Sobolev.Foundations.PoincareW1p.Core
