import Homogenization.Deterministic.CoarsePoincareRHS.AveragedLocal.DescendantsAverage
import Homogenization.Deterministic.CoarsePoincareRHS.AveragedLocal.ComponentBoundsBasic
import Homogenization.Deterministic.CoarsePoincareRHS.AveragedLocal.LocalizedEnergyForce
