module

public import Homogenization.Deterministic.CoarsePoincareRHS.AveragedLocal.DescendantsAverage
public import Homogenization.Deterministic.CoarsePoincareRHS.AveragedLocal.ComponentBoundsBasic
public import Homogenization.Deterministic.CoarsePoincareRHS.AveragedLocal.LocalizedEnergyForce
