module

public import Homogenization.Deterministic.CoarsePoincareRHS.FinalTheorems.NoteStepAndConstants
public import Homogenization.Deterministic.CoarsePoincareRHS.FinalTheorems.ExpandedAndElliptic
public import Homogenization.Deterministic.CoarsePoincareRHS.FinalTheorems.ZeroDirichletEnergy
