import Homogenization.Deterministic.CoarsePoincareRHS.FinalTheorems.NoteStepAndConstants
import Homogenization.Deterministic.CoarsePoincareRHS.FinalTheorems.ExpandedAndElliptic
import Homogenization.Deterministic.CoarsePoincareRHS.FinalTheorems.ZeroDirichletEnergy
