import Homogenization.Deterministic.CoarsePoincareRHS.LocalNoteTerms.Stepping
import Homogenization.Deterministic.CoarsePoincareRHS.LocalNoteTerms.Bounded
import Homogenization.Deterministic.CoarsePoincareRHS.LocalNoteTerms.Intrinsic
