import Homogenization.Probability.RegCoeffField.Restriction

/-!
# The local-to-restriction σ-algebra bridge

This file supplies the σ-algebra comparison

`LocalSigmaR U ≤ RestrictionSigmaR U hU`

(`localSigmaR_le_restrictionSigmaR`), the P5 gate of the carrier redesign.  It is
the missing link between the two local carrier σ-algebras:

* `LocalSigmaR U` — generated by entry-test preimages against probes supported in
  `U` — is where the honest AEE-slice measurability lives
  (`SliceMeasurability.lean`);
* `RestrictionSigmaR U hU` — the comap along the restriction endomorphism
  `restrictReg U hU` — is the measurable local σ-algebra defining
  `IsRestrictionLocalRandomVariable`.

The comparison holds because a localized entry-test generator factors through the
restriction endomorphism: for a probe supported in `U`, the restriction leaves the
entry test unchanged (`entryTestR_eq_restrictReg_of_support`), so the generator is
`RestrictionSigmaR`-measurable.  Consequently every `LocalSigmaR U`-measurable
observable is a genuine restriction-local random variable — in particular the AEE
slice event, and (once its raw measurability machinery is re-aimed onto the
carrier) the coarse-grained energy `Mu`.

The final section connects the entry-test generators to the set-integral form
`∫_U w · a(·)_{ij}` in which the raw `Mu`/`toHilbertMatrixL2` measurability
machinery expresses its dense-probe inner products
(`entryTestR_eq_setIntegral_of_support`), so that those inner products are
`LocalSigmaR U`-measurable — hence restriction-local — functions of the carrier
field.

Reference: the paper (Armstrong–Kuusi–Loher, to appear).
-/

namespace Homogenization

open MeasureTheory

noncomputable section

variable {d : ℕ}

/-! ## Restriction leaves supported entry tests unchanged -/

/-- For a probe supported in `U`, the restriction endomorphism leaves the entry
test unchanged: the entry integrand `a(·)_{ij} · φ` only sees the values of `a` on
`U`, where `restrictReg U hU a` agrees with `a`. -/
theorem entryTestR_eq_restrictReg_of_support {U : Set (Vec d)} (hU : MeasurableSet U)
    (i j : Fin d) {φ : Vec d → ℝ} (hsupp : Function.support φ ⊆ U) (a : RegCoeffField d) :
    entryTestR i j φ a = entryTestR i j φ (restrictReg U hU a) := by
  rw [entryTestR_restrictReg]
  have hEq : Set.indicator U φ = φ := by
    funext x
    by_cases hx : x ∈ U
    · simp [Set.indicator_of_mem hx]
    · have hx0 : x ∉ Function.support φ := fun h => hx (hsupp h)
      rw [Function.mem_support, not_not] at hx0
      simp [Set.indicator_of_notMem hx, hx0]
  rw [hEq]

/-- A localized entry-test generator is `RestrictionSigmaR U hU`-measurable: it
factors through the (restriction-local-measurable) restriction endomorphism. -/
theorem measurable_entryTestR_restrictionSigmaR {U : Set (Vec d)} (hU : MeasurableSet U)
    (i j : Fin d) {φ : Vec d → ℝ} (hφ : IsProbeR φ) (hsupp : Function.support φ ⊆ U) :
    @Measurable (RegCoeffField d) ℝ (RestrictionSigmaR U hU) _ (entryTestR i j φ) := by
  have hfac : (entryTestR i j φ) = fun a => entryTestR i j φ (restrictReg U hU a) := by
    funext a; exact entryTestR_eq_restrictReg_of_support hU i j hsupp a
  rw [hfac]
  exact (measurable_entryTestR i j hφ).comp (measurable_restrictReg_restrictionSigmaR U hU)

/-! ## The bridge -/

/-- **The local entry-test σ-algebra is coarser than the restriction σ-algebra.**
Each `LocalSigmaR U` generator is a supported entry-test preimage, hence
`RestrictionSigmaR U hU`-measurable.  This is the P5 gate: every
`LocalSigmaR U`-measurable observable is a restriction-local random variable. -/
theorem localSigmaR_le_restrictionSigmaR (U : Set (Vec d)) (hU : MeasurableSet U) :
    LocalSigmaR U ≤ RestrictionSigmaR U hU := by
  refine MeasurableSpace.generateFrom_le ?_
  rintro s ⟨i, j, φ, hφ, hsupp, t, ht, rfl⟩
  exact measurable_entryTestR_restrictionSigmaR hU i j hφ hsupp ht

/-- A carrier observable that is `LocalSigmaR U`-measurable is
`RestrictionSigmaR U hU`-measurable.  (For `β = ℝ` this is exactly the
`IsRestrictionLocalRandomVariable` predicate of Chapter 4.) -/
theorem measurable_restrictionSigmaR_of_measurable_localSigmaR {β : Type*} [MeasurableSpace β]
    {U : Set (Vec d)} (hU : MeasurableSet U) {X : RegCoeffField d → β}
    (hX : @Measurable (RegCoeffField d) β (LocalSigmaR U) _ X) :
    @Measurable (RegCoeffField d) β (RestrictionSigmaR U hU) _ X :=
  hX.mono (localSigmaR_le_restrictionSigmaR U hU) le_rfl

/-! ## Entry tests as set integrals (the `Mu`/`toHilbertMatrixL2` orientation) -/

/-- For a probe supported in `U`, the entry test equals the set integral
`∫_U φ · a(·)_{ij}` — the exact orientation in which the raw
`Mu`/`toHilbertMatrixL2` measurability machinery expresses its dense-probe inner
products (`inner_toScalarL2_hilbertMatrixL2Entry_eq_setIntegral`).  Hence each such
inner product is a `LocalSigmaR U`-measurable — and so restriction-local —
function of the carrier field. -/
theorem entryTestR_eq_setIntegral_of_support {U : Set (Vec d)} (hU : MeasurableSet U)
    (i j : Fin d) {φ : Vec d → ℝ} (hsupp : Function.support φ ⊆ U) (a : RegCoeffField d) :
    entryTestR i j φ a = ∫ x in U, φ x * a x i j ∂volume := by
  unfold entryTestR
  rw [← integral_indicator hU]
  refine integral_congr_ae (Filter.Eventually.of_forall (fun x => ?_))
  by_cases hx : x ∈ U
  · simp only [Set.indicator_of_mem hx]; ring
  · have hx0 : x ∉ Function.support φ := fun h => hx (hsupp h)
    rw [Function.mem_support, not_not] at hx0
    simp [Set.indicator_of_notMem hx, hx0]

/-- The supported set-integral functional `a ↦ ∫_U φ · a(·)_{ij}` is
`RestrictionSigmaR U hU`-measurable. -/
theorem measurable_setIntegral_restrictionSigmaR {U : Set (Vec d)} (hU : MeasurableSet U)
    (i j : Fin d) {φ : Vec d → ℝ} (hφ : IsProbeR φ) (hsupp : Function.support φ ⊆ U) :
    @Measurable (RegCoeffField d) ℝ (RestrictionSigmaR U hU) _
      (fun a => ∫ x in U, φ x * a x i j ∂volume) := by
  have hEq : (fun a : RegCoeffField d => ∫ x in U, φ x * a x i j ∂volume)
      = entryTestR i j φ := by
    funext a; exact (entryTestR_eq_setIntegral_of_support hU i j hsupp a).symm
  rw [hEq]
  exact measurable_entryTestR_restrictionSigmaR hU i j hφ hsupp

end

end Homogenization
