import Homogenization.Probability.RegCoeffField.Sigma

/-!
# Smooth integral sigma algebras on regular coefficient fields

This file isolates the smooth, compactly supported entry-test information used
by source-facing integral-local probability APIs.  It intentionally installs no
ambient measurable-space instance and remains separate from pointwise and
restriction-local constructions.
-/

namespace Homogenization

noncomputable section

variable {d : ℕ}

set_option warn.classDefReducibility false in
/-- The local sigma algebra generated by entry tests against globally smooth,
compactly supported probes whose topological support lies in `U`. -/
def SmoothLocalSigmaR (U : Set (Vec d)) : MeasurableSpace (RegCoeffField d) :=
  MeasurableSpace.generateFrom
    {s | ∃ (i j : Fin d) (φ : Vec d → ℝ),
      ContDiff ℝ (⊤ : ℕ∞) φ ∧ HasCompactSupport φ ∧ tsupport φ ⊆ U ∧
      ∃ t : Set ℝ, MeasurableSet t ∧ s = entryTestR i j φ ⁻¹' t}

set_option warn.classDefReducibility false in
/-- The global smooth integral sigma algebra on regular coefficient fields. -/
def SmoothGlobalSigmaR (d : ℕ) : MeasurableSpace (RegCoeffField d) :=
  SmoothLocalSigmaR (d := d) Set.univ

/-- Smooth local integral information is monotone under enlargement of the
observation set. -/
theorem smoothLocalSigmaR_mono {U V : Set (Vec d)} (hUV : U ⊆ V) :
    SmoothLocalSigmaR U ≤ SmoothLocalSigmaR V := by
  refine MeasurableSpace.generateFrom_le ?_
  rintro s ⟨i, j, φ, hφ_smooth, hφ_compact, hφ_support, t, ht, rfl⟩
  exact MeasurableSpace.measurableSet_generateFrom
    ⟨i, j, φ, hφ_smooth, hφ_compact, hφ_support.trans hUV, t, ht, rfl⟩

/-- Every smooth local integral event is measurable for the global smooth
integral sigma algebra. -/
theorem smoothLocalSigmaR_le_smoothGlobalSigmaR (U : Set (Vec d)) :
    SmoothLocalSigmaR U ≤ SmoothGlobalSigmaR d :=
  smoothLocalSigmaR_mono (U := U) (V := Set.univ) (fun _ _ => Set.mem_univ _)

/-- The smooth support-local entry-test sigma algebra is contained in the
existing enriched entry-test sigma algebra. -/
theorem smoothLocalSigmaR_le_localSigmaR (U : Set (Vec d)) :
    SmoothLocalSigmaR U ≤ LocalSigmaR U := by
  refine MeasurableSpace.generateFrom_le ?_
  rintro s ⟨i, j, φ, hφ_smooth, hφ_compact, hφ_support, t, ht, rfl⟩
  exact MeasurableSpace.measurableSet_generateFrom
    ⟨i, j, φ, IsProbeR.of_smooth hφ_smooth hφ_compact,
      (subset_tsupport φ).trans hφ_support, t, ht, rfl⟩

end

end Homogenization
