import Homogenization.Sobolev.Foundations.CubeReflection.Folding.Geometry
import Homogenization.Sobolev.Foundations.CubeReflection.Folding.BlockDecomposition
import Homogenization.Sobolev.Foundations.CubeReflection.Folding.BlockIntegrals
