import Homogenization.Ambient.HilbertFinite
import Homogenization.Geometry.BoundaryLayer
import Homogenization.Geometry.CubeMeasure
import Homogenization.Geometry.CubeMetric
import Homogenization.Probability.RandomField
import Homogenization.Probability.RandomFieldMeasurability
import Homogenization.Probability.SeparableHilbertMeasurability
import Mathlib.MeasureTheory.Function.LpSpace.Complete
import Mathlib.MeasureTheory.MeasurableSpace.Constructions
import Mathlib.MeasureTheory.Measure.SeparableMeasure

namespace Homogenization

/-- The `k`-th countable quantitative ellipticity slice on a fixed spatial set.

This is the countable surface used by the probability layer after a qualitative
locally uniformly elliptic field has been restricted to a bounded observation
domain. -/
def QuantitativeEllipticSlice {d : ℕ} (U : Set (Vec d)) (k : ℕ)
    (a : CoeffField d) : Prop :=
  IsEllipticFieldOn ((k + 1 : ℝ)⁻¹) (k + 1 : ℝ) U a

/-- Essential/a.e. ellipticity on a deterministic observation set.

This is the probability-facing version of `IsEllipticFieldOn`: the restricted
coefficient field is measurable, but ellipticity is required only
`volumeMeasureOn U`-almost everywhere.  This is the legacy essential variant
used by constructions that identify coefficient fields up to spatial a.e.
agreement. -/
def IsEssentiallyEllipticFieldOn {d : ℕ} (lam Lam : ℝ) (U : Set (Vec d))
    (a : CoeffField d) : Prop :=
  by
    classical
    exact
      MeasurableSet U ∧
        Measurable (fun x i j => if x ∈ U then a x i j else 0) ∧
          ∀ᵐ x ∂ volumeMeasureOn U, IsEllipticMatrix lam Lam (a x)

/--
Spatial a.e. ellipticity on a deterministic observation set, with only an
a.e.-strongly-measurable coefficient representative.

This is the boundary-stable variant needed by Ch. 5: unlike
`IsEssentiallyEllipticFieldOn`, it is insensitive to changing the coefficient
field on a null boundary layer.
-/
def IsAEEllipticFieldOn {d : ℕ} (lam Lam : ℝ) (U : Set (Vec d))
    (a : CoeffField d) : Prop :=
  MeasurableSet U ∧
    (∀ i j : Fin d,
      MeasureTheory.AEStronglyMeasurable
        (fun x : Vec d => restrictCoeffField U a x i j) (volumeMeasureOn U)) ∧
      ∀ᵐ x ∂ volumeMeasureOn U, IsEllipticMatrix lam Lam (a x)

/-- The `k`-th essential quantitative ellipticity slice.  Unlike
`QuantitativeEllipticSlice`, this records the quantitative ellipticity bounds
only a.e. on `U`, matching the probability sigma lane generated by local
integral tests. -/
def EssentialQuantitativeEllipticSlice {d : ℕ} (U : Set (Vec d)) (k : ℕ)
    (a : CoeffField d) : Prop :=
  IsEssentiallyEllipticFieldOn ((k + 1 : ℝ)⁻¹) (k + 1 : ℝ) U a

/-- The `k`-th quantitative slice for the boundary-stable spatial-a.e.
ellipticity predicate.  This is the countable version of
`IsAEEllipticFieldOn`, intended for law-relative Chapter 4/5 plumbing where
only a.e.-strong measurability is available. -/
def AEEQuantitativeEllipticSlice {d : ℕ} (U : Set (Vec d)) (k : ℕ)
    (a : CoeffField d) : Prop :=
  IsAEEllipticFieldOn ((k + 1 : ℝ)⁻¹) (k + 1 : ℝ) U a

namespace IsEllipticFieldOn

/--
Transport pointwise ellipticity of the translated coefficient field on `U`
back to pointwise ellipticity of the original coefficient field on the
translated set.  The a.e. Ch5 law-data lane uses this only as a deterministic
translation step before weakening to `IsAEEllipticFieldOn`; it does not add any
quantitative ellipticity input beyond the original constants.
-/
theorem translateSet_of_translateCoeffField {d : ℕ} {lam Lam : ℝ}
    {U : Set (Vec d)} {a : CoeffField d} (z : Vec d)
    (hEll : IsEllipticFieldOn lam Lam U (translateCoeffField z a)) :
    IsEllipticFieldOn lam Lam (translateSet z U) a := by
  classical
  refine ⟨?_, ?_⟩
  · have hshift : Measurable fun x : Vec d => x - z :=
      (continuous_id.sub continuous_const).measurable
    have hcomp :
        Measurable
          (((fun y : Vec d => fun i j =>
                if y ∈ U then (translateCoeffField z a) y i j else 0) ∘
              fun x : Vec d => x - z)) :=
      hEll.1.comp hshift
    have hEq :
        (((fun y : Vec d => fun i j =>
                if y ∈ U then (translateCoeffField z a) y i j else 0) ∘
              fun x : Vec d => x - z)) =
          (fun x i j => if x ∈ translateSet z U then a x i j else 0) := by
      funext x i j
      dsimp [translateCoeffField]
      have hmem : x ∈ translateSet z U ↔ x - z ∈ U :=
        mem_translateSet_iff_sub_mem
      by_cases hxU : x - z ∈ U
      · have hxT : x ∈ translateSet z U := hmem.mpr hxU
        simp [hxU, hxT]
      · have hxT : x ∉ translateSet z U := fun hx => hxU (hmem.mp hx)
        simp [hxU, hxT]
    rw [hEq] at hcomp
    exact hcomp
  · intro x hx
    have hxU : x - z ∈ U := mem_translateSet_iff_sub_mem.mp hx
    have hmat := hEll.2 (x - z) hxU
    have hsub_add : x - z + z = x := by
      ext k
      simp [sub_eq_add_neg, add_assoc]
    simpa [translateCoeffField, hsub_add] using hmat

end IsEllipticFieldOn

namespace IsEssentiallyEllipticFieldOn

theorem measurableSet {d : ℕ} {lam Lam : ℝ} {U : Set (Vec d)} {a : CoeffField d}
    (h : IsEssentiallyEllipticFieldOn lam Lam U a) :
    MeasurableSet U :=
  h.1

theorem ae_isEllipticMatrix {d : ℕ} {lam Lam : ℝ} {U : Set (Vec d)}
    {a : CoeffField d} (h : IsEssentiallyEllipticFieldOn lam Lam U a) :
    ∀ᵐ x ∂ volumeMeasureOn U, IsEllipticMatrix lam Lam (a x) :=
  h.2.2

theorem of_isEllipticFieldOn {d : ℕ} {lam Lam : ℝ} {U : Set (Vec d)}
    {a : CoeffField d} (h : IsEllipticFieldOn lam Lam U a) :
    IsEssentiallyEllipticFieldOn lam Lam U a := by
  have hU : MeasurableSet U := measurableSet_of_isEllipticFieldOn h
  refine ⟨hU, h.1, ?_⟩
  exact (MeasureTheory.ae_restrict_iff' hU).2
    (Filter.Eventually.of_forall fun x hx => h.2 x hx)

theorem mono_constants {d : ℕ} {lam Lam lam' Lam' : ℝ} {U : Set (Vec d)}
    {a : CoeffField d} (h : IsEssentiallyEllipticFieldOn lam Lam U a)
    (hlam'_pos : 0 < lam') (hlam'_le : lam' ≤ lam) (hLam_le : Lam ≤ Lam') :
    IsEssentiallyEllipticFieldOn lam' Lam' U a := by
  refine ⟨h.measurableSet, h.2.1, ?_⟩
  exact h.ae_isEllipticMatrix.mono fun _x hx =>
    hx.mono hlam'_pos hlam'_le hLam_le

end IsEssentiallyEllipticFieldOn

namespace IsAEEllipticFieldOn

theorem measurableSet {d : ℕ} {lam Lam : ℝ} {U : Set (Vec d)} {a : CoeffField d}
    (h : IsAEEllipticFieldOn lam Lam U a) :
    MeasurableSet U :=
  h.1

theorem aestronglyMeasurable_restrictCoeffField_apply {d : ℕ} {lam Lam : ℝ}
    {U : Set (Vec d)} {a : CoeffField d}
    (h : IsAEEllipticFieldOn lam Lam U a) (i j : Fin d) :
    MeasureTheory.AEStronglyMeasurable
      (fun x : Vec d => restrictCoeffField U a x i j) (volumeMeasureOn U) :=
  h.2.1 i j

theorem ae_isEllipticMatrix {d : ℕ} {lam Lam : ℝ} {U : Set (Vec d)}
    {a : CoeffField d} (h : IsAEEllipticFieldOn lam Lam U a) :
    ∀ᵐ x ∂ volumeMeasureOn U, IsEllipticMatrix lam Lam (a x) :=
  h.2.2

theorem of_isEssentiallyEllipticFieldOn {d : ℕ} {lam Lam : ℝ} {U : Set (Vec d)}
    {a : CoeffField d} (h : IsEssentiallyEllipticFieldOn lam Lam U a) :
    IsAEEllipticFieldOn lam Lam U a := by
  classical
  have hmeas :
      ∀ i j : Fin d,
        MeasureTheory.AEStronglyMeasurable
          (fun x : Vec d => restrictCoeffField U a x i j) (volumeMeasureOn U) := by
    intro i j
    have hcoord :
        Measurable fun x : Vec d => if x ∈ U then a x i j else 0 := by
      simpa using (measurable_pi_iff.mp (measurable_pi_iff.mp h.2.1 i) j)
    have hcoord' :
        Measurable fun x : Vec d => restrictCoeffField U a x i j := by
      convert hcoord using 1
      funext x
      by_cases hx : x ∈ U <;> simp [restrictCoeffField, hx]
    exact hcoord'.aestronglyMeasurable
  exact ⟨h.1, hmeas, h.2.2⟩

theorem of_isEllipticFieldOn {d : ℕ} {lam Lam : ℝ} {U : Set (Vec d)}
    {a : CoeffField d} (h : IsEllipticFieldOn lam Lam U a) :
    IsAEEllipticFieldOn lam Lam U a :=
  of_isEssentiallyEllipticFieldOn
    (IsEssentiallyEllipticFieldOn.of_isEllipticFieldOn h)

theorem mono_constants {d : ℕ} {lam Lam lam' Lam' : ℝ} {U : Set (Vec d)}
    {a : CoeffField d} (h : IsAEEllipticFieldOn lam Lam U a)
    (hlam'_pos : 0 < lam') (hlam'_le : lam' ≤ lam) (hLam_le : Lam ≤ Lam') :
    IsAEEllipticFieldOn lam' Lam' U a := by
  refine ⟨h.measurableSet, h.2.1, ?_⟩
  exact h.ae_isEllipticMatrix.mono fun _x hx =>
    hx.mono hlam'_pos hlam'_le hLam_le

theorem mono {d : ℕ} {lam Lam : ℝ} {U V : Set (Vec d)} {a : CoeffField d}
    (h : IsAEEllipticFieldOn lam Lam U a) (hV : MeasurableSet V) (hVU : V ⊆ U) :
    IsAEEllipticFieldOn lam Lam V a := by
  classical
  refine ⟨hV, ?_, ?_⟩
  · intro i j
    have hsub :
        MeasureTheory.AEStronglyMeasurable
          (fun x : Vec d => restrictCoeffField U a x i j) (volumeMeasureOn V) := by
      simpa [volumeMeasureOn] using
        (h.aestronglyMeasurable_restrictCoeffField_apply i j).mono_set hVU
    refine hsub.congr ?_
    filter_upwards [MeasureTheory.ae_restrict_mem hV] with x hxV
    have hxU : x ∈ U := hVU hxV
    simp [restrictCoeffField, hxV, hxU]
  · exact
      Filter.Eventually.filter_mono
        (MeasureTheory.ae_mono
          (by simpa [volumeMeasureOn] using
            MeasureTheory.Measure.restrict_mono hVU le_rfl))
        h.ae_isEllipticMatrix

/-- Finite unions preserve spatial a.e. ellipticity when the same quantitative
constants work on every member of the finite family. -/
theorem biUnion_finset {d : ℕ} {ι : Type*} {lam Lam : ℝ}
    (s : Finset ι) {U : ι → Set (Vec d)} {a : CoeffField d}
    (h : ∀ i ∈ s, IsAEEllipticFieldOn lam Lam (U i) a) :
    IsAEEllipticFieldOn lam Lam (⋃ i ∈ s, U i) a := by
  classical
  let V : Set (Vec d) := ⋃ i ∈ s, U i
  have hVmeas : MeasurableSet V := by
    dsimp [V]
    exact Finset.measurableSet_biUnion s fun i hi => (h i hi).measurableSet
  refine ⟨hVmeas, ?_, ?_⟩
  · intro p q
    change MeasureTheory.AEStronglyMeasurable
      (fun x : Vec d => restrictCoeffField V a x p q) (MeasureTheory.volume.restrict V)
    have hEach :
        ∀ i : {i // i ∈ s},
          MeasureTheory.AEStronglyMeasurable
            (fun x : Vec d => restrictCoeffField V a x p q)
            (MeasureTheory.volume.restrict (U i.1)) := by
      intro i
      have hAEM :
          MeasureTheory.AEStronglyMeasurable
            (fun x : Vec d => restrictCoeffField (U i.1) a x p q)
            (MeasureTheory.volume.restrict (U i.1)) := by
        simpa [volumeMeasureOn] using
          (h i.1 i.2).aestronglyMeasurable_restrictCoeffField_apply p q
      refine hAEM.congr ?_
      filter_upwards [MeasureTheory.ae_restrict_mem (h i.1 i.2).measurableSet] with x hx
      have hxV : x ∈ V := by
        exact Set.mem_iUnion.mpr ⟨i.1, Set.mem_iUnion.mpr ⟨i.2, hx⟩⟩
      simp [restrictCoeffField, hx, hxV]
    have hUnion :
        MeasureTheory.AEStronglyMeasurable
          (fun x : Vec d => restrictCoeffField V a x p q)
          (MeasureTheory.volume.restrict (⋃ i : {i // i ∈ s}, U i.1)) :=
      MeasureTheory.AEStronglyMeasurable.iUnion hEach
    have hSet : (⋃ i : {i // i ∈ s}, U i.1) = V := by
      ext x
      constructor
      · intro hx
        rcases Set.mem_iUnion.mp hx with ⟨i, hxU⟩
        exact Set.mem_iUnion.mpr ⟨i.1, Set.mem_iUnion.mpr ⟨i.2, hxU⟩⟩
      · intro hx
        rcases Set.mem_iUnion.mp hx with ⟨i, hxi⟩
        rcases Set.mem_iUnion.mp hxi with ⟨hi, hxU⟩
        exact Set.mem_iUnion.mpr ⟨⟨i, hi⟩, hxU⟩
    simpa only [hSet] using hUnion
  · change ∀ᵐ x ∂ MeasureTheory.volume.restrict V,
      IsEllipticMatrix lam Lam (a x)
    have hEach :
        ∀ i ∈ s,
          ∀ᵐ x ∂ MeasureTheory.volume.restrict (U i),
            IsEllipticMatrix lam Lam (a x) := by
      intro i hi
      simpa [volumeMeasureOn] using (h i hi).ae_isEllipticMatrix
    have hUnion :=
      (MeasureTheory.ae_restrict_biUnion_finset_iff
        (μ := MeasureTheory.volume) U s
        (fun x : Vec d => IsEllipticMatrix lam Lam (a x))).2 hEach
    simpa [V] using hUnion

/-- Finite unions preserve spatial a.e. ellipticity with explicit combined
constants: the lower constant is the finite infimum of the local lower
constants, and the upper constant is the finite supremum of the local upper
constants. -/
theorem exists_biUnion_finset {d : ℕ} {ι : Type*} (s : Finset ι)
    (hs : s.Nonempty) {U : ι → Set (Vec d)} {a : CoeffField d}
    (h : ∀ i ∈ s,
      ∃ lam Lam : ℝ,
        0 < lam ∧ lam ≤ Lam ∧ IsAEEllipticFieldOn lam Lam (U i) a) :
    ∃ lam Lam : ℝ,
      0 < lam ∧ lam ≤ Lam ∧
        IsAEEllipticFieldOn lam Lam (⋃ i ∈ s, U i) a := by
  classical
  let t : Finset {i // i ∈ s} := s.attach
  have ht : t.Nonempty := hs.attach
  let lamOf : {i // i ∈ s} → ℝ := fun i => Classical.choose (h i.1 i.2)
  let LamOf : {i // i ∈ s} → ℝ := fun i =>
    Classical.choose (Classical.choose_spec (h i.1 i.2))
  let lam : ℝ := t.inf' ht lamOf
  let Lam : ℝ := t.sup' ht LamOf
  have hdata :
      ∀ i : {i // i ∈ s},
        0 < lamOf i ∧ lamOf i ≤ LamOf i ∧
          IsAEEllipticFieldOn (lamOf i) (LamOf i) (U i.1) a := by
    intro i
    simpa [lamOf, LamOf] using
      Classical.choose_spec (Classical.choose_spec (h i.1 i.2))
  have hlam_pos : 0 < lam := by
    refine (Finset.lt_inf'_iff (s := t) (H := ht) (f := lamOf)).2 ?_
    intro i _hi
    exact (hdata i).1
  have hlam_le_Lam : lam ≤ Lam := by
    rcases ht with ⟨i, hi⟩
    exact
      le_trans (Finset.inf'_le (s := t) (f := lamOf) hi)
        (le_trans (hdata i).2.1
          (Finset.le_sup' (s := t) (f := LamOf) hi))
  refine ⟨lam, Lam, hlam_pos, hlam_le_Lam, ?_⟩
  refine biUnion_finset (lam := lam) (Lam := Lam) s ?_
  intro i hi
  let I : {i // i ∈ s} := ⟨i, hi⟩
  have hI : I ∈ t := by
    simp [t]
  have hlam_le : lam ≤ lamOf I :=
    Finset.inf'_le (s := t) (f := lamOf) hI
  have hLam_le : LamOf I ≤ Lam :=
    Finset.le_sup' (s := t) (f := LamOf) hI
  simpa [I] using
    (hdata I).2.2.mono_constants hlam_pos hlam_le hLam_le

theorem translateSet_of_translateCoeffField {d : ℕ} {lam Lam : ℝ}
    {U : Set (Vec d)} {a : CoeffField d} (z : Vec d)
    (h : IsAEEllipticFieldOn lam Lam U (translateCoeffField z a)) :
    IsAEEllipticFieldOn lam Lam (translateSet z U) a := by
  classical
  have hUtrans : MeasurableSet (translateSet z U) := by
    have hpre :
        MeasurableSet ((fun x : Vec d => x - z) ⁻¹' U) :=
      h.measurableSet.preimage (continuous_id.sub continuous_const).measurable
    simpa [preimage_subRight_eq_translateSet] using hpre
  refine ⟨hUtrans, ?_, ?_⟩
  · intro i j
    have hcomp :
        MeasureTheory.AEStronglyMeasurable
          ((fun y : Vec d => restrictCoeffField U (translateCoeffField z a) y i j) ∘
            fun x : Vec d => x - z)
          (volumeMeasureOn (translateSet z U)) :=
      (h.aestronglyMeasurable_restrictCoeffField_apply i j).comp_measurePreserving
        (measurePreserving_subRight_restrict_translateSet (d := d) z U)
    refine hcomp.congr ?_
    filter_upwards with x
    have hmem : x ∈ translateSet z U ↔ x - z ∈ U :=
      mem_translateSet_iff_sub_mem
    have hsub_add : x - z + z = x := by
      ext k
      simp [sub_eq_add_neg, add_assoc]
    by_cases hxU : x - z ∈ U
    · have hxT : x ∈ translateSet z U := hmem.mpr hxU
      simp [Function.comp, restrictCoeffField, translateCoeffField, hxU, hxT]
    · have hxT : x ∉ translateSet z U := fun hx => hxU (hmem.mp hx)
      simp [Function.comp, restrictCoeffField, hxU, hxT]
  · have hmap :
        MeasureTheory.Measure.map (fun x : Vec d => x - z)
            (volumeMeasureOn (translateSet z U)) =
          volumeMeasureOn U := by
      simpa [volumeMeasureOn] using
        (measurePreserving_subRight_restrict_translateSet (d := d) z U).map_eq
    have haeMap :
        ∀ᵐ y ∂MeasureTheory.Measure.map (fun x : Vec d => x - z)
            (volumeMeasureOn (translateSet z U)),
          IsEllipticMatrix lam Lam ((translateCoeffField z a) y) := by
      simpa [hmap] using h.ae_isEllipticMatrix
    have haeSub :
        ∀ᵐ x ∂volumeMeasureOn (translateSet z U),
          IsEllipticMatrix lam Lam ((translateCoeffField z a) (x - z)) :=
      MeasureTheory.ae_of_ae_map
        ((Homeomorph.subRight z).measurable.aemeasurable) haeMap
    filter_upwards [haeSub] with x hx
    have hsub_add : x - z + z = x := by
      ext k
      simp [sub_eq_add_neg, add_assoc]
    simpa [translateCoeffField, hsub_add] using hx

theorem memVectorL2_matVecMul {d : ℕ} {lam Lam : ℝ}
    {U : Set (Vec d)} {a : CoeffField d} (h : IsAEEllipticFieldOn lam Lam U a)
    {f : Vec d → Vec d} (hf : MemVectorL2 U f) :
    MemVectorL2 U (fun x => matVecMul (a x) (f x)) := by
  classical
  rw [MemVectorL2] at hf ⊢
  refine (MeasureTheory.memLp_pi_iff).2 ?_
  intro i
  refine MeasureTheory.memLp_finset_sum
    (s := Finset.univ)
    (f := fun j : Fin d => fun x : Vec d => a x i j * f x j) ?_
  intro j _hj
  have hfj : MeasureTheory.MemLp (fun x => f x j) 2 (volumeMeasureOn U) :=
    (MeasureTheory.memLp_pi_iff.mp hf) j
  have hcoeff_aesm :
      MeasureTheory.AEStronglyMeasurable (fun x : Vec d => a x i j)
        (volumeMeasureOn U) := by
    refine (h.aestronglyMeasurable_restrictCoeffField_apply i j).congr ?_
    filter_upwards [MeasureTheory.ae_restrict_mem h.measurableSet] with x hx
    simp [restrictCoeffField, hx]
  have hterm_meas :
      MeasureTheory.AEStronglyMeasurable (fun x => a x i j * f x j)
        (volumeMeasureOn U) :=
    hcoeff_aesm.mul hfj.aestronglyMeasurable
  have hbound :
      ∀ᵐ x ∂ volumeMeasureOn U, ‖a x i j * f x j‖ ≤ Lam * ‖f x j‖ := by
    filter_upwards [h.ae_isEllipticMatrix] with x hxEll
    have hcoeff_le : |a x i j| ≤ Lam := abs_apply_le_of_isEllipticMatrix hxEll i j
    calc
      ‖a x i j * f x j‖ = |a x i j| * ‖f x j‖ := by
        rw [norm_mul, Real.norm_eq_abs]
      _ ≤ Lam * ‖f x j‖ := mul_le_mul_of_nonneg_right hcoeff_le (norm_nonneg _)
  simpa using MeasureTheory.MemLp.of_le_mul hfj hterm_meas hbound

/-- Spatial a.e. ellipticity on the open core of a triadic cube extends to the
half-open cube, since the two restricted volume measures agree. -/
theorem cubeSet_of_openCubeSet {d : ℕ} {lam Lam : ℝ}
    {Q : TriadicCube d} {a : CoeffField d}
    (h : IsAEEllipticFieldOn lam Lam (openCubeSet Q) a) :
    IsAEEllipticFieldOn lam Lam (cubeSet Q) a := by
  classical
  have hMeasure :
      volumeMeasureOn (cubeSet Q) = volumeMeasureOn (openCubeSet Q) := by
    simpa [volumeMeasureOn] using volume_restrict_cubeSet_eq_volume_restrict_openCubeSet Q
  refine ⟨measurableSet_cubeSet Q, ?_, ?_⟩
  · intro i j
    rw [hMeasure]
    have hEq :
        (fun x : Vec d => restrictCoeffField (openCubeSet Q) a x i j) =ᵐ[
          volumeMeasureOn (openCubeSet Q)]
          (fun x : Vec d => restrictCoeffField (cubeSet Q) a x i j) := by
      filter_upwards [MeasureTheory.ae_restrict_mem (measurableSet_openCubeSet Q)] with x hx
      have hxCube : x ∈ cubeSet Q := openCubeSet_subset_cubeSet Q hx
      simp [restrictCoeffField, hx, hxCube]
    exact (h.aestronglyMeasurable_restrictCoeffField_apply i j).congr hEq
  · rw [hMeasure]
    exact h.ae_isEllipticMatrix

theorem cubeSet_of_isEllipticFieldOn_openCubeSet {d : ℕ} {lam Lam : ℝ}
    {Q : TriadicCube d} {a : CoeffField d}
    (h : IsEllipticFieldOn lam Lam (openCubeSet Q) a) :
    IsAEEllipticFieldOn lam Lam (cubeSet Q) a := by
  classical
  have hOpen : IsAEEllipticFieldOn lam Lam (openCubeSet Q) a :=
    of_isEllipticFieldOn h
  have hMeasure :
      volumeMeasureOn (cubeSet Q) = volumeMeasureOn (openCubeSet Q) := by
    simpa [volumeMeasureOn] using volume_restrict_cubeSet_eq_volume_restrict_openCubeSet Q
  refine ⟨measurableSet_cubeSet Q, ?_, ?_⟩
  · intro i j
    rw [hMeasure]
    have hEq :
        (fun x : Vec d => restrictCoeffField (openCubeSet Q) a x i j) =ᵐ[
          volumeMeasureOn (openCubeSet Q)]
          (fun x : Vec d => restrictCoeffField (cubeSet Q) a x i j) := by
      filter_upwards [MeasureTheory.ae_restrict_mem (measurableSet_openCubeSet Q)] with x hx
      have hxCube : x ∈ cubeSet Q := openCubeSet_subset_cubeSet Q hx
      simp [restrictCoeffField, hx, hxCube]
    exact (hOpen.aestronglyMeasurable_restrictCoeffField_apply i j).congr hEq
  · rw [hMeasure]
    exact hOpen.ae_isEllipticMatrix

theorem cubeSet_originCube_of_isEllipticFieldOn_openCubeSet_originCube {d : ℕ}
    {lam Lam : ℝ} {n : ℤ} {a : CoeffField d}
    (h : IsEllipticFieldOn lam Lam (openCubeSet (originCube d n)) a) :
    IsAEEllipticFieldOn lam Lam (cubeSet (originCube d n)) a :=
  cubeSet_of_isEllipticFieldOn_openCubeSet h

theorem of_localAgreementOn {d : ℕ} {lam Lam : ℝ} {U : Set (Vec d)}
    {a b : CoeffField d} (hab : LocalAgreementOn U a b)
    (h : IsAEEllipticFieldOn lam Lam U a) :
    IsAEEllipticFieldOn lam Lam U b := by
  refine ⟨h.1, ?_, ?_⟩
  · intro i j
    have hfun :
        (fun x : Vec d => restrictCoeffField U b x i j) =
          fun x : Vec d => restrictCoeffField U a x i j := by
      funext x
      by_cases hx : x ∈ U
      · simp [restrictCoeffField, hx, (hab x hx).symm]
      · simp [restrictCoeffField, hx]
    simpa [hfun] using h.2.1 i j
  · filter_upwards [h.2.2, MeasureTheory.ae_restrict_mem h.1] with x hxEll hxU
    simpa [hab x hxU] using hxEll

theorem iff_of_localAgreementOn {d : ℕ} {lam Lam : ℝ} {U : Set (Vec d)}
    {a b : CoeffField d} (hab : LocalAgreementOn U a b) :
    IsAEEllipticFieldOn lam Lam U a ↔ IsAEEllipticFieldOn lam Lam U b := by
  constructor
  · exact of_localAgreementOn hab
  · intro h
    exact of_localAgreementOn (fun x hx => (hab x hx).symm) h

theorem measurableSet_localSigma {d : ℕ} (lam Lam : ℝ) (U : Set (Vec d)) :
    @MeasurableSet (CoeffField d) (LocalSigma U)
      {a : CoeffField d | IsAEEllipticFieldOn lam Lam U a} :=
  MeasurableSpace.measurableSet_generateFrom
    (by
      intro a b hab
      exact iff_of_localAgreementOn (lam := lam) (Lam := Lam) hab)

end IsAEEllipticFieldOn

namespace QuantitativeEllipticSlice

theorem mono {d : ℕ} {U V : Set (Vec d)} {k : ℕ} {a : CoeffField d}
    (h : QuantitativeEllipticSlice U k a) (hV : MeasurableSet V) (hVU : V ⊆ U) :
    QuantitativeEllipticSlice V k a := by
  exact IsEllipticFieldOn.mono h hV hVU

/-- A raw pointwise quantitative slice set can be `LocalSigma U`-measurable only if
membership in that slice is invariant under pointwise changes outside `U`.
This records the exact compatibility condition imposed by the local
coefficient-field sigma algebra. -/
theorem eqOn_saturated_of_measurableSet_localSigma {d : ℕ} {U : Set (Vec d)}
    {k : ℕ} {a b : CoeffField d}
    (hmeas : @MeasurableSet (CoeffField d) (LocalSigma U)
      {c : CoeffField d | QuantitativeEllipticSlice U k c})
    (h : ∀ x, x ∈ U → a x = b x) :
    QuantitativeEllipticSlice U k a ↔ QuantitativeEllipticSlice U k b := by
  simpa using
    (mem_iff_of_measurableSet_localSigma_of_eqOn
      (U := U) (s := {c : CoeffField d | QuantitativeEllipticSlice U k c})
      hmeas h)

/-- The subtype sigma algebra inherited from the local coefficient-field sigma
algebra. We keep this as an explicit definition, rather than an instance, so
theorem statements choose the local lane deliberately. -/
def localMeasurableSpace {d : ℕ} (U : Set (Vec d)) (k : ℕ) :
    MeasurableSpace {a : CoeffField d // QuantitativeEllipticSlice U k a} :=
  MeasurableSpace.comap Subtype.val (LocalSigma U)

theorem measurable_val_localMeasurableSpace {d : ℕ} {U : Set (Vec d)} {k : ℕ} :
    @Measurable {a : CoeffField d // QuantitativeEllipticSlice U k a}
      (CoeffField d) (localMeasurableSpace U k) (LocalSigma U) Subtype.val :=
  comap_measurable Subtype.val

theorem memLp_restrictCoeffField {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    {a : CoeffField d} [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (h : QuantitativeEllipticSlice U k a) :
    MeasureTheory.MemLp
      (fun x i j => restrictCoeffField U a x i j) 2 (volumeMeasureOn U) := by
  classical
  rw [MeasureTheory.memLp_pi_iff]
  intro i
  rw [MeasureTheory.memLp_pi_iff]
  intro j
  have hmeas :
      Measurable fun x : Vec d => restrictCoeffField U a x i j := by
    convert (measurable_pi_iff.1 (measurable_pi_iff.1 h.1 i) j) using 1
    funext x
    by_cases hx : x ∈ U <;> simp [restrictCoeffField, hx]
  have hbound :
      ∀ᵐ x ∂ volumeMeasureOn U,
        ‖restrictCoeffField U a x i j‖ ≤ (k + 1 : ℝ) := by
    filter_upwards with x
    by_cases hx : x ∈ U
    · simpa [restrictCoeffField, hx, Real.norm_eq_abs] using
        abs_apply_le_of_isEllipticFieldOn h hx i j
    · have hk_nonneg : 0 ≤ (k + 1 : ℝ) := by positivity
      simp [restrictCoeffField, hx, hk_nonneg]
  exact MeasureTheory.MemLp.of_bound hmeas.aestronglyMeasurable (k + 1 : ℝ) hbound

noncomputable def toMatrixL2 {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (a : {a : CoeffField d // QuantitativeEllipticSlice U k a}) :
    MeasureTheory.Lp (Fin d → Fin d → ℝ) 2 (volumeMeasureOn U) :=
  a.2.memLp_restrictCoeffField.toLp (fun x i j => restrictCoeffField U a.1 x i j)

theorem memLp_hilbertMatrix_restrictCoeffField {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    {a : CoeffField d} [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (h : QuantitativeEllipticSlice U k a) :
    MeasureTheory.MemLp
      (fun x => HilbertMat.ofMat (restrictCoeffField U a x)) 2 (volumeMeasureOn U) := by
  let T : Mat d →L[ℝ] HilbertMat d :=
    ((HilbertMat.continuousLinearEquivMat d).symm).toContinuousLinearMap
  simpa [T] using T.comp_memLp' h.memLp_restrictCoeffField

noncomputable def toHilbertMatrixL2 {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (a : {a : CoeffField d // QuantitativeEllipticSlice U k a}) :
    MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U) :=
  a.2.memLp_hilbertMatrix_restrictCoeffField.toLp
    (fun x => HilbertMat.ofMat (restrictCoeffField U a.1 x))

/-- Strong Borel measurability of the coefficient-field `L²` realization follows from a
countable probe family that both separates the Hilbert norm and has measurable scalar
coordinates on the local slice sigma algebra. -/
theorem measurable_toHilbertMatrixL2_of_norm_eq_iSup_abs_inner {d : ℕ} {U : Set (Vec d)}
    {k : ℕ} [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (u : ℕ → MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U))
    (hu : DenseRange u)
    (hNormEq : ∀ f : MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U),
      ‖f‖ = ⨆ n : ℕ, |inner ℝ (u n) f|)
    (hInner : ∀ n : ℕ,
      @Measurable {a : CoeffField d // QuantitativeEllipticSlice U k a} ℝ
        (localMeasurableSpace U k) (borel ℝ)
        (fun a => inner ℝ (u n) (toHilbertMatrixL2 a))) :
    @Measurable {a : CoeffField d // QuantitativeEllipticSlice U k a}
      (MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U))
      (localMeasurableSpace U k) (borel _) toHilbertMatrixL2 := by
  haveI : Fact ((2 : ENNReal) ≠ ⊤) := ⟨ENNReal.ofNat_ne_top⟩
  let H := MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U)
  letI : MeasurableSpace H := borel H
  haveI : BorelSpace H := ⟨rfl⟩
  exact
    @measurable_of_measurable_inner_denseRange_of_norm_eq_iSup_abs_inner
      {a : CoeffField d // QuantitativeEllipticSlice U k a} H
      (localMeasurableSpace U k) _ _ _ _ _ u hu
      (F := toHilbertMatrixL2) hNormEq hInner

/-- Strong Borel measurability of the coefficient-field `L²` realization follows from
measurable scalar coordinates against any dense probe sequence in the Hilbert `L²` target. This
is the non-circular endpoint used by the fixed-competitor measurability cleanup. -/
theorem measurable_toHilbertMatrixL2_of_dense_inner {d : ℕ} {U : Set (Vec d)}
    {k : ℕ} [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (u : ℕ → MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U))
    (hu : DenseRange u)
    (hInner : ∀ n : ℕ,
      @Measurable {a : CoeffField d // QuantitativeEllipticSlice U k a} ℝ
        (localMeasurableSpace U k) (borel ℝ)
        (fun a => inner ℝ (u n) (toHilbertMatrixL2 a))) :
    @Measurable {a : CoeffField d // QuantitativeEllipticSlice U k a}
      (MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U))
      (localMeasurableSpace U k) (borel _) toHilbertMatrixL2 := by
  haveI : Fact ((2 : ENNReal) ≠ ⊤) := ⟨ENNReal.ofNat_ne_top⟩
  let H := MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U)
  letI : MeasurableSpace H := borel H
  haveI : BorelSpace H := ⟨rfl⟩
  exact
    @measurable_of_measurable_inner_denseRange_polish
      {a : CoeffField d // QuantitativeEllipticSlice U k a} H
      (localMeasurableSpace U k) _ _ _ _ _ u hu
      (F := toHilbertMatrixL2) hInner

theorem coeFn_toMatrixL2 {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (a : {a : CoeffField d // QuantitativeEllipticSlice U k a}) :
    toMatrixL2 a =ᵐ[volumeMeasureOn U] fun x i j => restrictCoeffField U a.1 x i j :=
  MeasureTheory.MemLp.coeFn_toLp a.2.memLp_restrictCoeffField

theorem coeFn_toHilbertMatrixL2 {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (a : {a : CoeffField d // QuantitativeEllipticSlice U k a}) :
    toHilbertMatrixL2 a =ᵐ[volumeMeasureOn U]
      fun x => HilbertMat.ofMat (restrictCoeffField U a.1 x) :=
  MeasureTheory.MemLp.coeFn_toLp a.2.memLp_hilbertMatrix_restrictCoeffField

noncomputable def matrixL2Entry {d : ℕ} {U : Set (Vec d)} (i j : Fin d) :
    MeasureTheory.Lp (Fin d → Fin d → ℝ) 2 (volumeMeasureOn U) →L[ℝ] ScalarL2 U := by
  let row : (Fin d → Fin d → ℝ) →L[ℝ] (Fin d → ℝ) :=
    ContinuousLinearMap.proj (R := ℝ) i
  let entry : (Fin d → ℝ) →L[ℝ] ℝ :=
    ContinuousLinearMap.proj (R := ℝ) j
  exact (entry.comp row).compLpL 2 (volumeMeasureOn U)

noncomputable def hilbertMatrixL2Entry {d : ℕ} {U : Set (Vec d)} (i j : Fin d) :
    MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U) →L[ℝ] ScalarL2 U :=
  (HilbertMat.entryL i j).compLpL 2 (volumeMeasureOn U)

theorem coeFn_matrixL2Entry_toMatrixL2 {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (i j : Fin d) (a : {a : CoeffField d // QuantitativeEllipticSlice U k a}) :
    matrixL2Entry (U := U) i j (toMatrixL2 a) =ᵐ[volumeMeasureOn U]
      fun x => restrictCoeffField U a.1 x i j := by
  let row : (Fin d → Fin d → ℝ) →L[ℝ] (Fin d → ℝ) :=
    ContinuousLinearMap.proj (R := ℝ) i
  let entry : (Fin d → ℝ) →L[ℝ] ℝ :=
    ContinuousLinearMap.proj (R := ℝ) j
  have hcomp :
      matrixL2Entry (U := U) i j (toMatrixL2 a) =ᵐ[volumeMeasureOn U]
        fun x => (entry.comp row) (toMatrixL2 a x) := by
    simpa [matrixL2Entry, row, entry] using
      (ContinuousLinearMap.coeFn_compLpL
        (p := 2)
        (μ := volumeMeasureOn U)
        (L := entry.comp row)
        (f := toMatrixL2 a))
  filter_upwards [hcomp, coeFn_toMatrixL2 a] with x hcompx hcoeff
  rw [hcompx, hcoeff]
  simp [row, entry]

theorem coeFn_hilbertMatrixL2Entry_toHilbertMatrixL2 {d : ℕ} {U : Set (Vec d)}
    {k : ℕ} [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (i j : Fin d) (a : {a : CoeffField d // QuantitativeEllipticSlice U k a}) :
    hilbertMatrixL2Entry (U := U) i j (toHilbertMatrixL2 a) =ᵐ[volumeMeasureOn U]
      fun x => restrictCoeffField U a.1 x i j := by
  have hcomp :
      hilbertMatrixL2Entry (U := U) i j (toHilbertMatrixL2 a) =ᵐ[volumeMeasureOn U]
        fun x => HilbertMat.entryL i j (toHilbertMatrixL2 a x) := by
    simpa [hilbertMatrixL2Entry] using
      (ContinuousLinearMap.coeFn_compLpL
        (p := 2)
        (μ := volumeMeasureOn U)
        (L := HilbertMat.entryL i j)
        (f := toHilbertMatrixL2 a))
  filter_upwards [hcomp, coeFn_toHilbertMatrixL2 a] with x hcompx hcoeff
  rw [hcompx, hcoeff]
  simp

theorem inner_toScalarL2_matrixL2Entry_toMatrixL2_eq_setIntegral {d : ℕ}
    {U : Set (Vec d)} {k : ℕ} [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    {w : Vec d → ℝ} (hw : MemScalarL2 U w) (i j : Fin d)
    (a : {a : CoeffField d // QuantitativeEllipticSlice U k a}) :
    inner ℝ (toScalarL2 hw) (matrixL2Entry (U := U) i j (toMatrixL2 a)) =
      ∫ x in U, w x * a.1 x i j ∂MeasureTheory.volume := by
  rw [MeasureTheory.L2.inner_def]
  trans ∫ x, w x * restrictCoeffField U a.1 x i j ∂volumeMeasureOn U
  · refine MeasureTheory.integral_congr_ae ?_
    filter_upwards
        [coeFn_toScalarL2 hw,
         coeFn_matrixL2Entry_toMatrixL2 i j a]
      with x hweight hcoeff
    rw [hweight, hcoeff]
    change restrictCoeffField U a.1 x i j * w x = w x * restrictCoeffField U a.1 x i j
    ring
  · unfold volumeMeasureOn
    refine MeasureTheory.integral_congr_ae ?_
    filter_upwards [MeasureTheory.ae_restrict_mem
      (measurableSet_of_isEllipticFieldOn a.2)] with x hx
    simp [restrictCoeffField, hx]

theorem inner_toScalarL2_hilbertMatrixL2Entry_toHilbertMatrixL2_eq_setIntegral {d : ℕ}
    {U : Set (Vec d)} {k : ℕ} [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    {w : Vec d → ℝ} (hw : MemScalarL2 U w) (i j : Fin d)
    (a : {a : CoeffField d // QuantitativeEllipticSlice U k a}) :
    inner ℝ (toScalarL2 hw) (hilbertMatrixL2Entry (U := U) i j (toHilbertMatrixL2 a)) =
      ∫ x in U, w x * a.1 x i j ∂MeasureTheory.volume := by
  rw [MeasureTheory.L2.inner_def]
  trans ∫ x, w x * restrictCoeffField U a.1 x i j ∂volumeMeasureOn U
  · refine MeasureTheory.integral_congr_ae ?_
    filter_upwards
        [coeFn_toScalarL2 hw,
         coeFn_hilbertMatrixL2Entry_toHilbertMatrixL2 i j a]
      with x hweight hcoeff
    rw [hweight, hcoeff]
    change restrictCoeffField U a.1 x i j * w x = w x * restrictCoeffField U a.1 x i j
    ring
  · unfold volumeMeasureOn
    refine MeasureTheory.integral_congr_ae ?_
    filter_upwards [MeasureTheory.ae_restrict_mem
      (measurableSet_of_isEllipticFieldOn a.2)] with x hx
    simp [restrictCoeffField, hx]

theorem memScalarL2_hilbertMatrix_entry_of_memLp {d : ℕ} {U : Set (Vec d)}
    {g : Vec d → HilbertMat d}
    (hg : MeasureTheory.MemLp g 2 (volumeMeasureOn U)) (i j : Fin d) :
    MemScalarL2 U (fun x => HilbertMat.entryL i j (g x)) := by
  simpa [MemScalarL2, Function.comp_def] using
    (HilbertMat.entryL i j).comp_memLp' hg

theorem inner_toScalarL2_hilbertMatrixL2Entry_eq_integral {d : ℕ}
    {U : Set (Vec d)} {w : Vec d → ℝ} (hw : MemScalarL2 U w) (i j : Fin d)
    (A : MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U)) :
    inner ℝ (toScalarL2 hw) (hilbertMatrixL2Entry (U := U) i j A) =
      ∫ x, w x * A x i j ∂volumeMeasureOn U := by
  rw [MeasureTheory.L2.inner_def]
  have hentry :
      hilbertMatrixL2Entry (U := U) i j A =ᵐ[volumeMeasureOn U]
        fun x => HilbertMat.entryL i j (A x) := by
    simpa [hilbertMatrixL2Entry] using
      (ContinuousLinearMap.coeFn_compLpL
        (p := 2)
        (μ := volumeMeasureOn U)
        (L := HilbertMat.entryL i j)
        (f := A))
  refine MeasureTheory.integral_congr_ae ?_
  filter_upwards [coeFn_toScalarL2 hw, hentry] with x hweight hentryx
  rw [hweight, hentryx]
  change A x i j * w x = w x * A x i j
  ring

theorem integrable_hilbertMatrix_entry_mul {d : ℕ} {U : Set (Vec d)}
    {g : Vec d → HilbertMat d} (hg : MeasureTheory.MemLp g 2 (volumeMeasureOn U))
    (A : MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U)) (i j : Fin d) :
    MeasureTheory.Integrable (fun x => g x i j * A x i j) (volumeMeasureOn U) := by
  have hgij : MeasureTheory.MemLp (fun x => HilbertMat.entryL i j (g x)) 2
      (volumeMeasureOn U) := by
    simpa [Function.comp_def] using (HilbertMat.entryL i j).comp_memLp' hg
  have hAij : MeasureTheory.MemLp (fun x => HilbertMat.entryL i j (A x)) 2
      (volumeMeasureOn U) := by
    simpa [Function.comp_def] using
      (HilbertMat.entryL i j).comp_memLp' (MeasureTheory.Lp.memLp A)
  simpa using hgij.integrable_mul hAij

theorem integrable_hilbertMatrix_entry_sum {d : ℕ} {U : Set (Vec d)}
    {g : Vec d → HilbertMat d} (hg : MeasureTheory.MemLp g 2 (volumeMeasureOn U))
    (A : MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U)) (i : Fin d) :
    MeasureTheory.Integrable (fun x => ∑ j : Fin d, g x i j * A x i j)
      (volumeMeasureOn U) := by
  exact MeasureTheory.integrable_finset_sum _ fun j _ =>
    integrable_hilbertMatrix_entry_mul hg A i j

theorem inner_hilbertMatrixL2_eq_sum_entry_inner {d : ℕ} {U : Set (Vec d)}
    {g : Vec d → HilbertMat d}
    (hg : MeasureTheory.MemLp g 2 (volumeMeasureOn U))
    (A : MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U)) :
    inner ℝ (hg.toLp g) A =
      ∑ i : Fin d, ∑ j : Fin d,
        inner ℝ (toScalarL2 (memScalarL2_hilbertMatrix_entry_of_memLp (U := U) hg i j))
          (hilbertMatrixL2Entry (U := U) i j A) := by
  rw [MeasureTheory.L2.inner_def]
  trans ∫ x, inner ℝ (g x) (A x) ∂volumeMeasureOn U
  · refine MeasureTheory.integral_congr_ae ?_
    filter_upwards [MeasureTheory.MemLp.coeFn_toLp hg] with x hx
    rw [hx]
  calc
    ∫ x, inner ℝ (g x) (A x) ∂volumeMeasureOn U
        = ∫ x, ∑ i : Fin d, ∑ j : Fin d, g x i j * A x i j ∂volumeMeasureOn U := by
          apply MeasureTheory.integral_congr_ae
          filter_upwards with x
          simp [HilbertMat.inner_def]
    _ = ∑ i : Fin d, ∫ x, ∑ j : Fin d, g x i j * A x i j ∂volumeMeasureOn U := by
          rw [MeasureTheory.integral_finset_sum]
          intro i _
          exact integrable_hilbertMatrix_entry_sum hg A i
    _ = ∑ i : Fin d, ∑ j : Fin d, ∫ x, g x i j * A x i j ∂volumeMeasureOn U := by
          congr with i
          rw [MeasureTheory.integral_finset_sum]
          intro j _
          exact integrable_hilbertMatrix_entry_mul hg A i j
    _ = ∑ i : Fin d, ∑ j : Fin d,
          inner ℝ (toScalarL2 (memScalarL2_hilbertMatrix_entry_of_memLp (U := U) hg i j))
            (hilbertMatrixL2Entry (U := U) i j A) := by
          congr with i
          congr with j
          exact (inner_toScalarL2_hilbertMatrixL2Entry_eq_integral
            (memScalarL2_hilbertMatrix_entry_of_memLp (U := U) hg i j) i j A).symm

/-- Any positive quantitative ellipticity constants can be relaxed to one of
the countable natural-number slices. -/
theorem exists_of_isEllipticFieldOn {d : ℕ} {U : Set (Vec d)} {a : CoeffField d}
    {ε : ℝ} (hε_pos : 0 < ε) (hEll : IsEllipticFieldOn ε ε⁻¹ U a) :
    ∃ k : ℕ, QuantitativeEllipticSlice U k a := by
  obtain ⟨k, hk⟩ := exists_nat_gt ε⁻¹
  have hε_inv_le_k : ε⁻¹ ≤ (k : ℝ) := le_of_lt hk
  have hk_le_succ : (k : ℝ) ≤ (k + 1 : ℝ) := by
    exact_mod_cast Nat.le_succ k
  have hε_inv_le_succ : ε⁻¹ ≤ (k + 1 : ℝ) := hε_inv_le_k.trans hk_le_succ
  have hslice_lam_pos : 0 < ((k + 1 : ℝ)⁻¹) := by positivity
  have hslice_lam_le : ((k + 1 : ℝ)⁻¹) ≤ ε :=
    inv_le_of_inv_le₀ hε_pos hε_inv_le_succ
  exact ⟨k, hEll.mono_constants hslice_lam_pos hslice_lam_le hε_inv_le_succ⟩

end QuantitativeEllipticSlice

namespace EssentialQuantitativeEllipticSlice

theorem of_quantitative {d : ℕ} {U : Set (Vec d)} {k : ℕ} {a : CoeffField d}
    (h : QuantitativeEllipticSlice U k a) :
    EssentialQuantitativeEllipticSlice U k a :=
  IsEssentiallyEllipticFieldOn.of_isEllipticFieldOn h

/-- The subtype sigma algebra inherited from the local coefficient-field sigma
algebra, now for essential/a.e. quantitative slices. -/
def localMeasurableSpace {d : ℕ} (U : Set (Vec d)) (k : ℕ) :
    MeasurableSpace {a : CoeffField d // EssentialQuantitativeEllipticSlice U k a} :=
  MeasurableSpace.comap Subtype.val (LocalSigma U)

theorem measurable_val_localMeasurableSpace {d : ℕ} {U : Set (Vec d)} {k : ℕ} :
    @Measurable {a : CoeffField d // EssentialQuantitativeEllipticSlice U k a}
      (CoeffField d) (localMeasurableSpace U k) (LocalSigma U) Subtype.val :=
  comap_measurable Subtype.val

theorem measurableSet {d : ℕ} {U : Set (Vec d)} {k : ℕ} {a : CoeffField d}
    (h : EssentialQuantitativeEllipticSlice U k a) :
    MeasurableSet U :=
  h.1

theorem ae_isEllipticMatrix {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    {a : CoeffField d} (h : EssentialQuantitativeEllipticSlice U k a) :
    ∀ᵐ x ∂ volumeMeasureOn U,
      IsEllipticMatrix ((k + 1 : ℝ)⁻¹) (k + 1 : ℝ) (a x) :=
  h.2.2

theorem memLp_restrictCoeffField {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    {a : CoeffField d} [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (h : EssentialQuantitativeEllipticSlice U k a) :
    MeasureTheory.MemLp
      (fun x i j => restrictCoeffField U a x i j) 2 (volumeMeasureOn U) := by
  classical
  rw [MeasureTheory.memLp_pi_iff]
  intro i
  rw [MeasureTheory.memLp_pi_iff]
  intro j
  have hmeas :
      Measurable fun x : Vec d => restrictCoeffField U a x i j := by
    convert (measurable_pi_iff.1 (measurable_pi_iff.1 h.2.1 i) j)
      using 1
    funext x
    by_cases hx : x ∈ U <;> simp [restrictCoeffField, hx]
  have hbound :
      ∀ᵐ x ∂ volumeMeasureOn U,
        ‖restrictCoeffField U a x i j‖ ≤ (k + 1 : ℝ) := by
    filter_upwards
        [h.2.2,
         MeasureTheory.ae_restrict_mem h.1]
      with x hxEll hxU
    simpa [restrictCoeffField, hxU, Real.norm_eq_abs] using
      abs_apply_le_of_isEllipticMatrix hxEll i j
  exact MeasureTheory.MemLp.of_bound hmeas.aestronglyMeasurable (k + 1 : ℝ) hbound

theorem memLp_hilbertMatrix_restrictCoeffField {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    {a : CoeffField d} [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (h : EssentialQuantitativeEllipticSlice U k a) :
    MeasureTheory.MemLp
      (fun x => HilbertMat.ofMat (restrictCoeffField U a x)) 2 (volumeMeasureOn U) := by
  let T : Mat d →L[ℝ] HilbertMat d :=
    ((HilbertMat.continuousLinearEquivMat d).symm).toContinuousLinearMap
  simpa [T] using T.comp_memLp' h.memLp_restrictCoeffField

noncomputable def toHilbertMatrixL2 {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (a : {a : CoeffField d // EssentialQuantitativeEllipticSlice U k a}) :
    MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U) :=
  a.2.memLp_hilbertMatrix_restrictCoeffField.toLp
    (fun x => HilbertMat.ofMat (restrictCoeffField U a.1 x))

theorem coeFn_toHilbertMatrixL2 {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (a : {a : CoeffField d // EssentialQuantitativeEllipticSlice U k a}) :
    toHilbertMatrixL2 a =ᵐ[volumeMeasureOn U]
      fun x => HilbertMat.ofMat (restrictCoeffField U a.1 x) :=
  MeasureTheory.MemLp.coeFn_toLp a.2.memLp_hilbertMatrix_restrictCoeffField

/-- Any positive essential ellipticity constants can be relaxed to one of the
countable essential natural-number slices. -/
theorem exists_of_isEssentiallyEllipticFieldOn {d : ℕ} {U : Set (Vec d)}
    {a : CoeffField d} {ε : ℝ} (hε_pos : 0 < ε)
    (hEll : IsEssentiallyEllipticFieldOn ε ε⁻¹ U a) :
    ∃ k : ℕ, EssentialQuantitativeEllipticSlice U k a := by
  obtain ⟨k, hk⟩ := exists_nat_gt ε⁻¹
  have hε_inv_le_k : ε⁻¹ ≤ (k : ℝ) := le_of_lt hk
  have hk_le_succ : (k : ℝ) ≤ (k + 1 : ℝ) := by
    exact_mod_cast Nat.le_succ k
  have hε_inv_le_succ : ε⁻¹ ≤ (k + 1 : ℝ) := hε_inv_le_k.trans hk_le_succ
  have hslice_lam_pos : 0 < ((k + 1 : ℝ)⁻¹) := by positivity
  have hslice_lam_le : ((k + 1 : ℝ)⁻¹) ≤ ε :=
    inv_le_of_inv_le₀ hε_pos hε_inv_le_succ
  exact ⟨k, hEll.mono_constants hslice_lam_pos hslice_lam_le hε_inv_le_succ⟩

end EssentialQuantitativeEllipticSlice

namespace AEEQuantitativeEllipticSlice

/-- The subtype sigma algebra inherited from the local coefficient-field sigma
algebra, for the boundary-stable AEE quantitative slices. -/
def localMeasurableSpace {d : ℕ} (U : Set (Vec d)) (k : ℕ) :
    MeasurableSpace {a : CoeffField d // AEEQuantitativeEllipticSlice U k a} :=
  MeasurableSpace.comap Subtype.val (LocalSigma U)

theorem measurable_val_localMeasurableSpace {d : ℕ} {U : Set (Vec d)} {k : ℕ} :
    @Measurable {a : CoeffField d // AEEQuantitativeEllipticSlice U k a}
      (CoeffField d) (localMeasurableSpace U k) (LocalSigma U) Subtype.val :=
  comap_measurable Subtype.val

theorem measurableSet {d : ℕ} {U : Set (Vec d)} {k : ℕ} {a : CoeffField d}
    (h : AEEQuantitativeEllipticSlice U k a) :
    MeasurableSet U :=
  h.1

theorem aestronglyMeasurable_restrictCoeffField_apply {d : ℕ} {U : Set (Vec d)}
    {k : ℕ} {a : CoeffField d} (h : AEEQuantitativeEllipticSlice U k a)
    (i j : Fin d) :
    MeasureTheory.AEStronglyMeasurable
      (fun x : Vec d => restrictCoeffField U a x i j) (volumeMeasureOn U) :=
  h.2.1 i j

theorem ae_isEllipticMatrix {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    {a : CoeffField d} (h : AEEQuantitativeEllipticSlice U k a) :
    ∀ᵐ x ∂ volumeMeasureOn U,
      IsEllipticMatrix ((k + 1 : ℝ)⁻¹) (k + 1 : ℝ) (a x) :=
  h.2.2

theorem of_localAgreementOn {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    {a b : CoeffField d} (hab : LocalAgreementOn U a b)
    (h : AEEQuantitativeEllipticSlice U k a) :
    AEEQuantitativeEllipticSlice U k b := by
  refine ⟨h.1, ?_, ?_⟩
  · intro i j
    have hfun :
        (fun x : Vec d => restrictCoeffField U b x i j) =
          fun x : Vec d => restrictCoeffField U a x i j := by
      funext x
      by_cases hx : x ∈ U
      · simp [restrictCoeffField, hx, (hab x hx).symm]
      · simp [restrictCoeffField, hx]
    simpa [hfun] using h.2.1 i j
  · filter_upwards [h.2.2, MeasureTheory.ae_restrict_mem h.1] with x hxEll hxU
    simpa [hab x hxU] using hxEll

theorem iff_of_localAgreementOn {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    {a b : CoeffField d} (hab : LocalAgreementOn U a b) :
    AEEQuantitativeEllipticSlice U k a ↔ AEEQuantitativeEllipticSlice U k b := by
  constructor
  · exact of_localAgreementOn hab
  · intro h
    exact of_localAgreementOn (fun x hx => (hab x hx).symm) h

theorem measurableSet_localSigma {d : ℕ} (U : Set (Vec d)) (k : ℕ) :
    @MeasurableSet (CoeffField d) (LocalSigma U)
      {a : CoeffField d | AEEQuantitativeEllipticSlice U k a} :=
  MeasurableSpace.measurableSet_generateFrom
    (by
      intro a b hab
      exact iff_of_localAgreementOn (k := k) hab)

/-- AEE quantitative slices still give an `L²` coefficient realization: the
coordinate functions are only a.e.-strongly measurable, but the quantitative
ellipticity bound supplies the uniform `L²` estimate. -/
theorem memLp_restrictCoeffField {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    {a : CoeffField d} [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (h : AEEQuantitativeEllipticSlice U k a) :
    MeasureTheory.MemLp
      (fun x i j => restrictCoeffField U a x i j) 2 (volumeMeasureOn U) := by
  classical
  rw [MeasureTheory.memLp_pi_iff]
  intro i
  rw [MeasureTheory.memLp_pi_iff]
  intro j
  have hbound :
      ∀ᵐ x ∂ volumeMeasureOn U,
        ‖restrictCoeffField U a x i j‖ ≤ (k + 1 : ℝ) := by
    filter_upwards
        [h.ae_isEllipticMatrix,
         MeasureTheory.ae_restrict_mem h.measurableSet]
      with x hxEll hxU
    simpa [restrictCoeffField, hxU, Real.norm_eq_abs] using
      abs_apply_le_of_isEllipticMatrix hxEll i j
  exact
    MeasureTheory.MemLp.of_bound
      (h.aestronglyMeasurable_restrictCoeffField_apply i j)
      (k + 1 : ℝ) hbound

theorem memLp_hilbertMatrix_restrictCoeffField {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    {a : CoeffField d} [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (h : AEEQuantitativeEllipticSlice U k a) :
    MeasureTheory.MemLp
      (fun x => HilbertMat.ofMat (restrictCoeffField U a x)) 2 (volumeMeasureOn U) := by
  let T : Mat d →L[ℝ] HilbertMat d :=
    ((HilbertMat.continuousLinearEquivMat d).symm).toContinuousLinearMap
  simpa [T] using T.comp_memLp' h.memLp_restrictCoeffField

noncomputable def toHilbertMatrixL2 {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (a : {a : CoeffField d // AEEQuantitativeEllipticSlice U k a}) :
    MeasureTheory.Lp (HilbertMat d) 2 (volumeMeasureOn U) :=
  a.2.memLp_hilbertMatrix_restrictCoeffField.toLp
    (fun x => HilbertMat.ofMat (restrictCoeffField U a.1 x))

theorem coeFn_toHilbertMatrixL2 {d : ℕ} {U : Set (Vec d)} {k : ℕ}
    [MeasureTheory.IsFiniteMeasure (volumeMeasureOn U)]
    (a : {a : CoeffField d // AEEQuantitativeEllipticSlice U k a}) :
    toHilbertMatrixL2 a =ᵐ[volumeMeasureOn U]
      fun x => HilbertMat.ofMat (restrictCoeffField U a.1 x) :=
  MeasureTheory.MemLp.coeFn_toLp a.2.memLp_hilbertMatrix_restrictCoeffField

/-- Any positive spatial-a.e. ellipticity constants can be relaxed to one of
the countable AEE quantitative slices. -/
theorem exists_of_aeeEllipticOn {d : ℕ} {U : Set (Vec d)} {a : CoeffField d}
    {lam Lam : ℝ} (hlam_pos : 0 < lam)
    (hEll : IsAEEllipticFieldOn lam Lam U a) :
    ∃ k : ℕ, AEEQuantitativeEllipticSlice U k a := by
  obtain ⟨k, hk⟩ := exists_nat_gt (max lam⁻¹ Lam)
  have hmax_le_k : max lam⁻¹ Lam ≤ (k : ℝ) := le_of_lt hk
  have hlam_inv_le_k : lam⁻¹ ≤ (k : ℝ) :=
    (le_max_left lam⁻¹ Lam).trans hmax_le_k
  have hLam_le_k : Lam ≤ (k : ℝ) :=
    (le_max_right lam⁻¹ Lam).trans hmax_le_k
  have hk_le_succ : (k : ℝ) ≤ (k + 1 : ℝ) := by
    exact_mod_cast Nat.le_succ k
  have hlam_inv_le_succ : lam⁻¹ ≤ (k + 1 : ℝ) :=
    hlam_inv_le_k.trans hk_le_succ
  have hLam_le_succ : Lam ≤ (k + 1 : ℝ) :=
    hLam_le_k.trans hk_le_succ
  have hslice_lam_pos : 0 < ((k + 1 : ℝ)⁻¹) := by positivity
  have hslice_lam_le : ((k + 1 : ℝ)⁻¹) ≤ lam :=
    inv_le_of_inv_le₀ hlam_pos hlam_inv_le_succ
  exact ⟨k, hEll.mono_constants hslice_lam_pos hslice_lam_le hLam_le_succ⟩

end AEEQuantitativeEllipticSlice

namespace IsLocallyUniformlyElliptic

/-- Restrict local uniform ellipticity from a centered closed ball to a measurable
subset of that ball. -/
theorem exists_isEllipticFieldOn_of_subset_closedBall {d : ℕ} {a : CoeffField d}
    {U : Set (Vec d)} {R : ℝ} (hloc : IsLocallyUniformlyElliptic a) (hR : 1 ≤ R)
    (hU : MeasurableSet U) (hsub : U ⊆ Metric.closedBall (0 : Vec d) R) :
    ∃ ε : ℝ, 0 < ε ∧ ε ≤ 1 ∧ IsEllipticFieldOn ε ε⁻¹ U a := by
  obtain ⟨ε, hε_pos, hε_le_one, hEll⟩ := hloc R hR
  exact ⟨ε, hε_pos, hε_le_one, hEll.mono hU hsub⟩

theorem exists_isEllipticFieldOn_cubeSet_originCube {d : ℕ} {a : CoeffField d}
    (hloc : IsLocallyUniformlyElliptic a) (n : ℤ) :
    ∃ ε : ℝ, 0 < ε ∧ ε ≤ 1 ∧
      IsEllipticFieldOn ε ε⁻¹ (cubeSet (originCube d n)) a := by
  refine hloc.exists_isEllipticFieldOn_of_subset_closedBall
    (R := max 1 (cubeRadius (originCube d n))) (le_max_left _ _)
    (measurableSet_cubeSet (originCube d n)) ?_
  intro x hx
  have hx_ball :
      x ∈ Metric.closedBall (cubeCenter (originCube d n)) (cubeRadius (originCube d n)) :=
    cubeSet_subset_closedBall (originCube d n) hx
  have hx_ball_zero :
      x ∈ Metric.closedBall (0 : Vec d) (cubeRadius (originCube d n)) := by
    have hcenter : cubeCenter (originCube d n) = (0 : Vec d) := by
      ext i
      simp [cubeCenter, originCube]
    simpa [hcenter] using hx_ball
  exact Metric.closedBall_subset_closedBall
    (le_max_right (1 : ℝ) (cubeRadius (originCube d n))) hx_ball_zero

theorem exists_isEllipticFieldOn_openCubeSet_originCube {d : ℕ} {a : CoeffField d}
    (hloc : IsLocallyUniformlyElliptic a) (n : ℤ) :
    ∃ ε : ℝ, 0 < ε ∧ ε ≤ 1 ∧
      IsEllipticFieldOn ε ε⁻¹ (openCubeSet (originCube d n)) a := by
  obtain ⟨ε, hε_pos, hε_le_one, hEll⟩ :=
    hloc.exists_isEllipticFieldOn_cubeSet_originCube n
  exact ⟨ε, hε_pos, hε_le_one,
    hEll.mono (measurableSet_openCubeSet (originCube d n))
      (openCubeSet_subset_cubeSet (originCube d n))⟩

theorem exists_quantitativeEllipticSlice_cubeSet_originCube {d : ℕ} {a : CoeffField d}
    (hloc : IsLocallyUniformlyElliptic a) (n : ℤ) :
    ∃ k : ℕ, QuantitativeEllipticSlice (cubeSet (originCube d n)) k a := by
  obtain ⟨ε, hε_pos, -, hEll⟩ := hloc.exists_isEllipticFieldOn_cubeSet_originCube n
  exact QuantitativeEllipticSlice.exists_of_isEllipticFieldOn hε_pos hEll

theorem exists_quantitativeEllipticSlice_openCubeSet_originCube {d : ℕ}
    {a : CoeffField d} (hloc : IsLocallyUniformlyElliptic a) (n : ℤ) :
    ∃ k : ℕ, QuantitativeEllipticSlice (openCubeSet (originCube d n)) k a := by
  obtain ⟨ε, hε_pos, -, hEll⟩ := hloc.exists_isEllipticFieldOn_openCubeSet_originCube n
  exact QuantitativeEllipticSlice.exists_of_isEllipticFieldOn hε_pos hEll

theorem exists_essentialQuantitativeEllipticSlice_cubeSet_originCube {d : ℕ}
    {a : CoeffField d} (hloc : IsLocallyUniformlyElliptic a) (n : ℤ) :
    ∃ k : ℕ, EssentialQuantitativeEllipticSlice (cubeSet (originCube d n)) k a := by
  obtain ⟨k, hk⟩ := hloc.exists_quantitativeEllipticSlice_cubeSet_originCube n
  exact ⟨k, EssentialQuantitativeEllipticSlice.of_quantitative hk⟩

theorem exists_essentialQuantitativeEllipticSlice_openCubeSet_originCube {d : ℕ}
    {a : CoeffField d} (hloc : IsLocallyUniformlyElliptic a) (n : ℤ) :
    ∃ k : ℕ, EssentialQuantitativeEllipticSlice (openCubeSet (originCube d n)) k a := by
  obtain ⟨k, hk⟩ := hloc.exists_quantitativeEllipticSlice_openCubeSet_originCube n
  exact ⟨k, EssentialQuantitativeEllipticSlice.of_quantitative hk⟩

end IsLocallyUniformlyElliptic

theorem ae_exists_quantitativeEllipticSlice_cubeSet_originCube
    {d : ℕ} {P : MeasureTheory.Measure (CoeffField d)}
    (hloc : ∀ᵐ a ∂P, IsLocallyUniformlyElliptic a) (n : ℤ) :
    ∀ᵐ a ∂P, ∃ k : ℕ, QuantitativeEllipticSlice (cubeSet (originCube d n)) k a :=
  hloc.mono fun _a ha => ha.exists_quantitativeEllipticSlice_cubeSet_originCube n

theorem ae_exists_quantitativeEllipticSlice_openCubeSet_originCube
    {d : ℕ} {P : MeasureTheory.Measure (CoeffField d)}
    (hloc : ∀ᵐ a ∂P, IsLocallyUniformlyElliptic a) (n : ℤ) :
    ∀ᵐ a ∂P, ∃ k : ℕ, QuantitativeEllipticSlice (openCubeSet (originCube d n)) k a :=
  hloc.mono fun _a ha => ha.exists_quantitativeEllipticSlice_openCubeSet_originCube n

theorem ae_exists_essentialQuantitativeEllipticSlice_cubeSet_originCube
    {d : ℕ} {P : MeasureTheory.Measure (CoeffField d)}
    (hloc : ∀ᵐ a ∂P, IsLocallyUniformlyElliptic a) (n : ℤ) :
    ∀ᵐ a ∂P, ∃ k : ℕ,
      EssentialQuantitativeEllipticSlice (cubeSet (originCube d n)) k a :=
  hloc.mono fun _a ha => ha.exists_essentialQuantitativeEllipticSlice_cubeSet_originCube n

theorem ae_exists_essentialQuantitativeEllipticSlice_openCubeSet_originCube
    {d : ℕ} {P : MeasureTheory.Measure (CoeffField d)}
    (hloc : ∀ᵐ a ∂P, IsLocallyUniformlyElliptic a) (n : ℤ) :
    ∀ᵐ a ∂P, ∃ k : ℕ,
      EssentialQuantitativeEllipticSlice (openCubeSet (originCube d n)) k a :=
  hloc.mono fun _a ha => ha.exists_essentialQuantitativeEllipticSlice_openCubeSet_originCube n

/-- The least quantitative slice index selected from a total countable
slice-cover proof.  This is intentionally just the measurable-selection
bookkeeping; proving that raw slice membership sets are measurable is a
separate input. -/
noncomputable def quantitativeEllipticSliceIndex
    {Ω : Type*} {d : ℕ} (U : Set (Vec d)) (A : Ω → CoeffField d)
    (hcover : ∀ ω : Ω, ∃ k : ℕ, QuantitativeEllipticSlice U k (A ω)) :
    Ω → ℕ := by
  classical
  exact fun ω => Nat.find (hcover ω)

theorem quantitativeEllipticSliceIndex_spec
    {Ω : Type*} {d : ℕ} (U : Set (Vec d)) (A : Ω → CoeffField d)
    (hcover : ∀ ω : Ω, ∃ k : ℕ, QuantitativeEllipticSlice U k (A ω))
    (ω : Ω) :
    QuantitativeEllipticSlice U (quantitativeEllipticSliceIndex U A hcover ω) (A ω) := by
  classical
  unfold quantitativeEllipticSliceIndex
  exact Nat.find_spec (hcover ω)

theorem measurable_quantitativeEllipticSliceIndex_of_measurableSet
    {Ω : Type*} [MeasurableSpace Ω] {d : ℕ} (U : Set (Vec d)) (A : Ω → CoeffField d)
    (hcover : ∀ ω : Ω, ∃ k : ℕ, QuantitativeEllipticSlice U k (A ω))
    (hSliceMeas :
      ∀ k : ℕ, MeasurableSet {ω : Ω | QuantitativeEllipticSlice U k (A ω)}) :
    Measurable (quantitativeEllipticSliceIndex U A hcover) := by
  classical
  unfold quantitativeEllipticSliceIndex
  exact measurable_find hcover hSliceMeas

/-- The least essential quantitative slice index selected from a total
countable cover.  This is the a.e.-elliptic replacement for
`quantitativeEllipticSliceIndex` in the probability handoff. -/
noncomputable def essentialQuantitativeEllipticSliceIndex
    {Ω : Type*} {d : ℕ} (U : Set (Vec d)) (A : Ω → CoeffField d)
    (hcover : ∀ ω : Ω, ∃ k : ℕ, EssentialQuantitativeEllipticSlice U k (A ω)) :
    Ω → ℕ := by
  classical
  exact fun ω => Nat.find (hcover ω)

theorem essentialQuantitativeEllipticSliceIndex_spec
    {Ω : Type*} {d : ℕ} (U : Set (Vec d)) (A : Ω → CoeffField d)
    (hcover : ∀ ω : Ω, ∃ k : ℕ, EssentialQuantitativeEllipticSlice U k (A ω))
    (ω : Ω) :
    EssentialQuantitativeEllipticSlice U
      (essentialQuantitativeEllipticSliceIndex U A hcover ω) (A ω) := by
  classical
  unfold essentialQuantitativeEllipticSliceIndex
  exact Nat.find_spec (hcover ω)

theorem measurable_essentialQuantitativeEllipticSliceIndex_of_measurableSet
    {Ω : Type*} [MeasurableSpace Ω] {d : ℕ} (U : Set (Vec d)) (A : Ω → CoeffField d)
    (hcover : ∀ ω : Ω, ∃ k : ℕ, EssentialQuantitativeEllipticSlice U k (A ω))
    (hSliceMeas :
      ∀ k : ℕ, MeasurableSet {ω : Ω | EssentialQuantitativeEllipticSlice U k (A ω)}) :
    Measurable (essentialQuantitativeEllipticSliceIndex U A hcover) := by
  classical
  unfold essentialQuantitativeEllipticSliceIndex
  exact measurable_find hcover hSliceMeas

/-- The least AEE quantitative slice index selected from a total countable
cover.  This is the boundary-stable analogue of
`essentialQuantitativeEllipticSliceIndex`; applications to Chapter 4 laws first
restrict to the full-measure support on which the cover is available. -/
noncomputable def aeeQuantitativeEllipticSliceIndex
    {Ω : Type*} {d : ℕ} (U : Set (Vec d)) (A : Ω → CoeffField d)
    (hcover : ∀ ω : Ω, ∃ k : ℕ, AEEQuantitativeEllipticSlice U k (A ω)) :
    Ω → ℕ := by
  classical
  exact fun ω => Nat.find (hcover ω)

theorem aeeQuantitativeEllipticSliceIndex_spec
    {Ω : Type*} {d : ℕ} (U : Set (Vec d)) (A : Ω → CoeffField d)
    (hcover : ∀ ω : Ω, ∃ k : ℕ, AEEQuantitativeEllipticSlice U k (A ω))
    (ω : Ω) :
    AEEQuantitativeEllipticSlice U
      (aeeQuantitativeEllipticSliceIndex U A hcover ω) (A ω) := by
  classical
  unfold aeeQuantitativeEllipticSliceIndex
  exact Nat.find_spec (hcover ω)

theorem measurable_aeeQuantitativeEllipticSliceIndex_of_measurableSet
    {Ω : Type*} [MeasurableSpace Ω] {d : ℕ} (U : Set (Vec d)) (A : Ω → CoeffField d)
    (hcover : ∀ ω : Ω, ∃ k : ℕ, AEEQuantitativeEllipticSlice U k (A ω))
    (hSliceMeas :
      ∀ k : ℕ, MeasurableSet {ω : Ω | AEEQuantitativeEllipticSlice U k (A ω)}) :
    Measurable (aeeQuantitativeEllipticSliceIndex U A hcover) := by
  classical
  unfold aeeQuantitativeEllipticSliceIndex
  exact measurable_find hcover hSliceMeas

end Homogenization
