import Homogenization.Deterministic.CoarseCaccioppoli.CutoffProduct.SplitPairing.Centered
import Homogenization.Deterministic.CoarseCaccioppoli.CutoffProduct.SplitPairing.Scalar
import Homogenization.Deterministic.CoarseCaccioppoli.CutoffProduct.SplitPairing.Vector
import Homogenization.Deterministic.CoarseCaccioppoli.CutoffProduct.SplitPairing.VectorFullDual
