module

public import Homogenization.Deterministic.CoarseCaccioppoli.CutoffProduct.SplitPairing.Centered
public import Homogenization.Deterministic.CoarseCaccioppoli.CutoffProduct.SplitPairing.Scalar
public import Homogenization.Deterministic.CoarseCaccioppoli.CutoffProduct.SplitPairing.Vector
public import Homogenization.Deterministic.CoarseCaccioppoli.CutoffProduct.SplitPairing.VectorFullDual
