import Homogenization.Sobolev.Foundations.CubeNeumannW22CZ.VectorFieldAndApex.WeakEquationHelpers
import Homogenization.Sobolev.Foundations.CubeNeumannW22CZ.VectorFieldAndApex.BlockFold
import Homogenization.Sobolev.Foundations.CubeNeumannW22CZ.VectorFieldAndApex.ReflectedEqCellSlab
import Homogenization.Sobolev.Foundations.CubeNeumannW22CZ.VectorFieldAndApex.BlockGlobalAndApex
