import Homogenization.Probability.Source.Coarse

/-!
# Null-set semantics of the integral-local σ-algebra

The coarse source's `localSigma` is generated by integral observables.  This
leaf module records the resulting null-set semantics without changing the
foundational definition in `Coarse.lean`.
-/

namespace Homogenization.Source.Coarse

open MeasureTheory

noncomputable section

/-- On a volume-null measurable set, every integral generator of `localSigma`
is constant, so the integral-local σ-algebra is bottom. -/
theorem localSigma_eq_bot_of_volume_eq_zero {d : ℕ} {U : Set (Vec d)}
    (hU : MeasurableSet U) (hvol : volume U = 0) :
    localSigma U hU = ⊥ := by
  apply le_antisymm
  · unfold localSigma
    refine MeasurableSpace.generateFrom_le ?_
    rintro s ⟨e, e', φ, hφ, hφU, t, ht, rfl⟩
    have hφ_zero : φ =ᵐ[volume] 0 := by
      change ∀ᵐ x ∂volume, φ x = 0
      rw [ae_iff]
      apply measure_mono_null ?_ hvol
      intro x hx
      exact hφU (subset_tsupport _ hx)
    have htest_zero : ∀ a : Carrier d, bilinearTest e e' φ a = 0 := by
      intro a
      unfold bilinearTest
      apply integral_eq_zero_of_ae
      filter_upwards [hφ_zero] with x hx
      simp [hx]
    by_cases ht0 : (0 : ℝ) ∈ t
    · rw [MeasurableSpace.measurableSet_bot_iff]
      right
      ext a
      simp [htest_zero a, ht0]
    · rw [MeasurableSpace.measurableSet_bot_iff]
      left
      ext a
      simp [htest_zero a, ht0]
  · exact bot_le

/-- Integral-local singleton information is trivial, while restriction point
evaluation remains observable: a singleton has bottom `localSigma`. -/
theorem localSigma_singleton_eq_bot {d : ℕ} [NeZero d] (x : Vec d) :
    localSigma ({x} : Set (Vec d)) (MeasurableSet.singleton x) = ⊥ :=
  localSigma_eq_bot_of_volume_eq_zero (MeasurableSet.singleton x)
    (measure_singleton x)

end

end Homogenization.Source.Coarse
