module

public import Homogenization.HighContrast.EntryScale.DeterministicAlgebra.P1
public import Homogenization.HighContrast.EntryScale.DeterministicAlgebra.P2
public import Homogenization.HighContrast.EntryScale.DeterministicAlgebra.P3
public import Homogenization.HighContrast.EntryScale.DeterministicAlgebra.P4
