import Homogenization.HighContrast.EntryScale.RawHighContrastEnergy.P1
import Homogenization.HighContrast.EntryScale.RawHighContrastEnergy.P2
import Homogenization.HighContrast.EntryScale.RawHighContrastEnergy.P3
