import Homogenization.CoarseGraining.ResponseIdentities.Foundations
import Homogenization.CoarseGraining.ResponseIdentities.AverageFormulas
import Homogenization.CoarseGraining.ResponseIdentities.Existence
import Homogenization.CoarseGraining.ResponseIdentities.ConvexAverageFormulas
import Homogenization.CoarseGraining.ResponseIdentities.Homogeneity
