module

public import Homogenization.Deterministic.CoarsePoincare.Setup.Conversions
public import Homogenization.Deterministic.CoarsePoincare.Setup.UniformBounds
public import Homogenization.Deterministic.CoarsePoincare.Setup.EnergyControls
public import Homogenization.Deterministic.CoarsePoincare.Setup.HarmonicAndData
